/* eslint-disable */

export const AllTypesProps: Record<string,any> = {
	Boolean_comparison_exp:{

	},
	Float_comparison_exp:{

	},
	Int_comparison_exp:{

	},
	String_comparison_exp:{

	},
	authProviderRequests:{
		options:{

		}
	},
	authProviderRequests_aggregate_fields:{
		count:{
			columns:"authProviderRequests_select_column"
		}
	},
	authProviderRequests_append_input:{
		options:"jsonb"
	},
	authProviderRequests_bool_exp:{
		_and:"authProviderRequests_bool_exp",
		_not:"authProviderRequests_bool_exp",
		_or:"authProviderRequests_bool_exp",
		id:"uuid_comparison_exp",
		options:"jsonb_comparison_exp"
	},
	authProviderRequests_constraint: "enum" as const,
	authProviderRequests_delete_at_path_input:{

	},
	authProviderRequests_delete_elem_input:{

	},
	authProviderRequests_delete_key_input:{

	},
	authProviderRequests_insert_input:{
		id:"uuid",
		options:"jsonb"
	},
	authProviderRequests_on_conflict:{
		constraint:"authProviderRequests_constraint",
		update_columns:"authProviderRequests_update_column",
		where:"authProviderRequests_bool_exp"
	},
	authProviderRequests_order_by:{
		id:"order_by",
		options:"order_by"
	},
	authProviderRequests_pk_columns_input:{
		id:"uuid"
	},
	authProviderRequests_prepend_input:{
		options:"jsonb"
	},
	authProviderRequests_select_column: "enum" as const,
	authProviderRequests_set_input:{
		id:"uuid",
		options:"jsonb"
	},
	authProviderRequests_stream_cursor_input:{
		initial_value:"authProviderRequests_stream_cursor_value_input",
		ordering:"cursor_ordering"
	},
	authProviderRequests_stream_cursor_value_input:{
		id:"uuid",
		options:"jsonb"
	},
	authProviderRequests_update_column: "enum" as const,
	authProviderRequests_updates:{
		_append:"authProviderRequests_append_input",
		_delete_at_path:"authProviderRequests_delete_at_path_input",
		_delete_elem:"authProviderRequests_delete_elem_input",
		_delete_key:"authProviderRequests_delete_key_input",
		_prepend:"authProviderRequests_prepend_input",
		_set:"authProviderRequests_set_input",
		where:"authProviderRequests_bool_exp"
	},
	authProviders:{
		userProviders:{
			distinct_on:"authUserProviders_select_column",
			order_by:"authUserProviders_order_by",
			where:"authUserProviders_bool_exp"
		},
		userProviders_aggregate:{
			distinct_on:"authUserProviders_select_column",
			order_by:"authUserProviders_order_by",
			where:"authUserProviders_bool_exp"
		}
	},
	authProviders_aggregate_fields:{
		count:{
			columns:"authProviders_select_column"
		}
	},
	authProviders_bool_exp:{
		_and:"authProviders_bool_exp",
		_not:"authProviders_bool_exp",
		_or:"authProviders_bool_exp",
		id:"String_comparison_exp",
		userProviders:"authUserProviders_bool_exp",
		userProviders_aggregate:"authUserProviders_aggregate_bool_exp"
	},
	authProviders_constraint: "enum" as const,
	authProviders_insert_input:{
		userProviders:"authUserProviders_arr_rel_insert_input"
	},
	authProviders_obj_rel_insert_input:{
		data:"authProviders_insert_input",
		on_conflict:"authProviders_on_conflict"
	},
	authProviders_on_conflict:{
		constraint:"authProviders_constraint",
		update_columns:"authProviders_update_column",
		where:"authProviders_bool_exp"
	},
	authProviders_order_by:{
		id:"order_by",
		userProviders_aggregate:"authUserProviders_aggregate_order_by"
	},
	authProviders_pk_columns_input:{

	},
	authProviders_select_column: "enum" as const,
	authProviders_set_input:{

	},
	authProviders_stream_cursor_input:{
		initial_value:"authProviders_stream_cursor_value_input",
		ordering:"cursor_ordering"
	},
	authProviders_stream_cursor_value_input:{

	},
	authProviders_update_column: "enum" as const,
	authProviders_updates:{
		_set:"authProviders_set_input",
		where:"authProviders_bool_exp"
	},
	authRefreshTokens_aggregate_bool_exp:{
		count:"authRefreshTokens_aggregate_bool_exp_count"
	},
	authRefreshTokens_aggregate_bool_exp_count:{
		arguments:"authRefreshTokens_select_column",
		filter:"authRefreshTokens_bool_exp",
		predicate:"Int_comparison_exp"
	},
	authRefreshTokens_aggregate_fields:{
		count:{
			columns:"authRefreshTokens_select_column"
		}
	},
	authRefreshTokens_aggregate_order_by:{
		count:"order_by",
		max:"authRefreshTokens_max_order_by",
		min:"authRefreshTokens_min_order_by"
	},
	authRefreshTokens_arr_rel_insert_input:{
		data:"authRefreshTokens_insert_input",
		on_conflict:"authRefreshTokens_on_conflict"
	},
	authRefreshTokens_bool_exp:{
		_and:"authRefreshTokens_bool_exp",
		_not:"authRefreshTokens_bool_exp",
		_or:"authRefreshTokens_bool_exp",
		createdAt:"timestamptz_comparison_exp",
		expiresAt:"timestamptz_comparison_exp",
		refreshToken:"uuid_comparison_exp",
		user:"users_bool_exp",
		userId:"uuid_comparison_exp"
	},
	authRefreshTokens_constraint: "enum" as const,
	authRefreshTokens_insert_input:{
		createdAt:"timestamptz",
		expiresAt:"timestamptz",
		refreshToken:"uuid",
		user:"users_obj_rel_insert_input",
		userId:"uuid"
	},
	authRefreshTokens_max_order_by:{
		createdAt:"order_by",
		expiresAt:"order_by",
		refreshToken:"order_by",
		userId:"order_by"
	},
	authRefreshTokens_min_order_by:{
		createdAt:"order_by",
		expiresAt:"order_by",
		refreshToken:"order_by",
		userId:"order_by"
	},
	authRefreshTokens_on_conflict:{
		constraint:"authRefreshTokens_constraint",
		update_columns:"authRefreshTokens_update_column",
		where:"authRefreshTokens_bool_exp"
	},
	authRefreshTokens_order_by:{
		createdAt:"order_by",
		expiresAt:"order_by",
		refreshToken:"order_by",
		user:"users_order_by",
		userId:"order_by"
	},
	authRefreshTokens_pk_columns_input:{
		refreshToken:"uuid"
	},
	authRefreshTokens_select_column: "enum" as const,
	authRefreshTokens_set_input:{
		createdAt:"timestamptz",
		expiresAt:"timestamptz",
		refreshToken:"uuid",
		userId:"uuid"
	},
	authRefreshTokens_stream_cursor_input:{
		initial_value:"authRefreshTokens_stream_cursor_value_input",
		ordering:"cursor_ordering"
	},
	authRefreshTokens_stream_cursor_value_input:{
		createdAt:"timestamptz",
		expiresAt:"timestamptz",
		refreshToken:"uuid",
		userId:"uuid"
	},
	authRefreshTokens_update_column: "enum" as const,
	authRefreshTokens_updates:{
		_set:"authRefreshTokens_set_input",
		where:"authRefreshTokens_bool_exp"
	},
	authRoles:{
		userRoles:{
			distinct_on:"authUserRoles_select_column",
			order_by:"authUserRoles_order_by",
			where:"authUserRoles_bool_exp"
		},
		userRoles_aggregate:{
			distinct_on:"authUserRoles_select_column",
			order_by:"authUserRoles_order_by",
			where:"authUserRoles_bool_exp"
		},
		usersByDefaultRole:{
			distinct_on:"users_select_column",
			order_by:"users_order_by",
			where:"users_bool_exp"
		},
		usersByDefaultRole_aggregate:{
			distinct_on:"users_select_column",
			order_by:"users_order_by",
			where:"users_bool_exp"
		}
	},
	authRoles_aggregate_fields:{
		count:{
			columns:"authRoles_select_column"
		}
	},
	authRoles_bool_exp:{
		_and:"authRoles_bool_exp",
		_not:"authRoles_bool_exp",
		_or:"authRoles_bool_exp",
		role:"String_comparison_exp",
		userRoles:"authUserRoles_bool_exp",
		userRoles_aggregate:"authUserRoles_aggregate_bool_exp",
		usersByDefaultRole:"users_bool_exp",
		usersByDefaultRole_aggregate:"users_aggregate_bool_exp"
	},
	authRoles_constraint: "enum" as const,
	authRoles_insert_input:{
		userRoles:"authUserRoles_arr_rel_insert_input",
		usersByDefaultRole:"users_arr_rel_insert_input"
	},
	authRoles_obj_rel_insert_input:{
		data:"authRoles_insert_input",
		on_conflict:"authRoles_on_conflict"
	},
	authRoles_on_conflict:{
		constraint:"authRoles_constraint",
		update_columns:"authRoles_update_column",
		where:"authRoles_bool_exp"
	},
	authRoles_order_by:{
		role:"order_by",
		userRoles_aggregate:"authUserRoles_aggregate_order_by",
		usersByDefaultRole_aggregate:"users_aggregate_order_by"
	},
	authRoles_pk_columns_input:{

	},
	authRoles_select_column: "enum" as const,
	authRoles_set_input:{

	},
	authRoles_stream_cursor_input:{
		initial_value:"authRoles_stream_cursor_value_input",
		ordering:"cursor_ordering"
	},
	authRoles_stream_cursor_value_input:{

	},
	authRoles_update_column: "enum" as const,
	authRoles_updates:{
		_set:"authRoles_set_input",
		where:"authRoles_bool_exp"
	},
	authUserProviders_aggregate_bool_exp:{
		count:"authUserProviders_aggregate_bool_exp_count"
	},
	authUserProviders_aggregate_bool_exp_count:{
		arguments:"authUserProviders_select_column",
		filter:"authUserProviders_bool_exp",
		predicate:"Int_comparison_exp"
	},
	authUserProviders_aggregate_fields:{
		count:{
			columns:"authUserProviders_select_column"
		}
	},
	authUserProviders_aggregate_order_by:{
		count:"order_by",
		max:"authUserProviders_max_order_by",
		min:"authUserProviders_min_order_by"
	},
	authUserProviders_arr_rel_insert_input:{
		data:"authUserProviders_insert_input",
		on_conflict:"authUserProviders_on_conflict"
	},
	authUserProviders_bool_exp:{
		_and:"authUserProviders_bool_exp",
		_not:"authUserProviders_bool_exp",
		_or:"authUserProviders_bool_exp",
		accessToken:"String_comparison_exp",
		createdAt:"timestamptz_comparison_exp",
		id:"uuid_comparison_exp",
		provider:"authProviders_bool_exp",
		providerId:"String_comparison_exp",
		providerUserId:"String_comparison_exp",
		refreshToken:"String_comparison_exp",
		updatedAt:"timestamptz_comparison_exp",
		user:"users_bool_exp",
		userId:"uuid_comparison_exp"
	},
	authUserProviders_constraint: "enum" as const,
	authUserProviders_insert_input:{
		createdAt:"timestamptz",
		id:"uuid",
		provider:"authProviders_obj_rel_insert_input",
		updatedAt:"timestamptz",
		user:"users_obj_rel_insert_input",
		userId:"uuid"
	},
	authUserProviders_max_order_by:{
		accessToken:"order_by",
		createdAt:"order_by",
		id:"order_by",
		providerId:"order_by",
		providerUserId:"order_by",
		refreshToken:"order_by",
		updatedAt:"order_by",
		userId:"order_by"
	},
	authUserProviders_min_order_by:{
		accessToken:"order_by",
		createdAt:"order_by",
		id:"order_by",
		providerId:"order_by",
		providerUserId:"order_by",
		refreshToken:"order_by",
		updatedAt:"order_by",
		userId:"order_by"
	},
	authUserProviders_on_conflict:{
		constraint:"authUserProviders_constraint",
		update_columns:"authUserProviders_update_column",
		where:"authUserProviders_bool_exp"
	},
	authUserProviders_order_by:{
		accessToken:"order_by",
		createdAt:"order_by",
		id:"order_by",
		provider:"authProviders_order_by",
		providerId:"order_by",
		providerUserId:"order_by",
		refreshToken:"order_by",
		updatedAt:"order_by",
		user:"users_order_by",
		userId:"order_by"
	},
	authUserProviders_pk_columns_input:{
		id:"uuid"
	},
	authUserProviders_select_column: "enum" as const,
	authUserProviders_set_input:{
		createdAt:"timestamptz",
		id:"uuid",
		updatedAt:"timestamptz",
		userId:"uuid"
	},
	authUserProviders_stream_cursor_input:{
		initial_value:"authUserProviders_stream_cursor_value_input",
		ordering:"cursor_ordering"
	},
	authUserProviders_stream_cursor_value_input:{
		createdAt:"timestamptz",
		id:"uuid",
		updatedAt:"timestamptz",
		userId:"uuid"
	},
	authUserProviders_update_column: "enum" as const,
	authUserProviders_updates:{
		_set:"authUserProviders_set_input",
		where:"authUserProviders_bool_exp"
	},
	authUserRoles_aggregate_bool_exp:{
		count:"authUserRoles_aggregate_bool_exp_count"
	},
	authUserRoles_aggregate_bool_exp_count:{
		arguments:"authUserRoles_select_column",
		filter:"authUserRoles_bool_exp",
		predicate:"Int_comparison_exp"
	},
	authUserRoles_aggregate_fields:{
		count:{
			columns:"authUserRoles_select_column"
		}
	},
	authUserRoles_aggregate_order_by:{
		count:"order_by",
		max:"authUserRoles_max_order_by",
		min:"authUserRoles_min_order_by"
	},
	authUserRoles_arr_rel_insert_input:{
		data:"authUserRoles_insert_input",
		on_conflict:"authUserRoles_on_conflict"
	},
	authUserRoles_bool_exp:{
		_and:"authUserRoles_bool_exp",
		_not:"authUserRoles_bool_exp",
		_or:"authUserRoles_bool_exp",
		createdAt:"timestamptz_comparison_exp",
		id:"uuid_comparison_exp",
		role:"String_comparison_exp",
		roleByRole:"authRoles_bool_exp",
		user:"users_bool_exp",
		userId:"uuid_comparison_exp"
	},
	authUserRoles_constraint: "enum" as const,
	authUserRoles_insert_input:{
		createdAt:"timestamptz",
		id:"uuid",
		roleByRole:"authRoles_obj_rel_insert_input",
		user:"users_obj_rel_insert_input",
		userId:"uuid"
	},
	authUserRoles_max_order_by:{
		createdAt:"order_by",
		id:"order_by",
		role:"order_by",
		userId:"order_by"
	},
	authUserRoles_min_order_by:{
		createdAt:"order_by",
		id:"order_by",
		role:"order_by",
		userId:"order_by"
	},
	authUserRoles_on_conflict:{
		constraint:"authUserRoles_constraint",
		update_columns:"authUserRoles_update_column",
		where:"authUserRoles_bool_exp"
	},
	authUserRoles_order_by:{
		createdAt:"order_by",
		id:"order_by",
		role:"order_by",
		roleByRole:"authRoles_order_by",
		user:"users_order_by",
		userId:"order_by"
	},
	authUserRoles_pk_columns_input:{
		id:"uuid"
	},
	authUserRoles_select_column: "enum" as const,
	authUserRoles_set_input:{
		createdAt:"timestamptz",
		id:"uuid",
		userId:"uuid"
	},
	authUserRoles_stream_cursor_input:{
		initial_value:"authUserRoles_stream_cursor_value_input",
		ordering:"cursor_ordering"
	},
	authUserRoles_stream_cursor_value_input:{
		createdAt:"timestamptz",
		id:"uuid",
		userId:"uuid"
	},
	authUserRoles_update_column: "enum" as const,
	authUserRoles_updates:{
		_set:"authUserRoles_set_input",
		where:"authUserRoles_bool_exp"
	},
	authUserSecurityKeys_aggregate_bool_exp:{
		count:"authUserSecurityKeys_aggregate_bool_exp_count"
	},
	authUserSecurityKeys_aggregate_bool_exp_count:{
		arguments:"authUserSecurityKeys_select_column",
		filter:"authUserSecurityKeys_bool_exp",
		predicate:"Int_comparison_exp"
	},
	authUserSecurityKeys_aggregate_fields:{
		count:{
			columns:"authUserSecurityKeys_select_column"
		}
	},
	authUserSecurityKeys_aggregate_order_by:{
		avg:"authUserSecurityKeys_avg_order_by",
		count:"order_by",
		max:"authUserSecurityKeys_max_order_by",
		min:"authUserSecurityKeys_min_order_by",
		stddev:"authUserSecurityKeys_stddev_order_by",
		stddev_pop:"authUserSecurityKeys_stddev_pop_order_by",
		stddev_samp:"authUserSecurityKeys_stddev_samp_order_by",
		sum:"authUserSecurityKeys_sum_order_by",
		var_pop:"authUserSecurityKeys_var_pop_order_by",
		var_samp:"authUserSecurityKeys_var_samp_order_by",
		variance:"authUserSecurityKeys_variance_order_by"
	},
	authUserSecurityKeys_arr_rel_insert_input:{
		data:"authUserSecurityKeys_insert_input",
		on_conflict:"authUserSecurityKeys_on_conflict"
	},
	authUserSecurityKeys_avg_order_by:{
		counter:"order_by"
	},
	authUserSecurityKeys_bool_exp:{
		_and:"authUserSecurityKeys_bool_exp",
		_not:"authUserSecurityKeys_bool_exp",
		_or:"authUserSecurityKeys_bool_exp",
		counter:"bigint_comparison_exp",
		credentialId:"String_comparison_exp",
		credentialPublicKey:"bytea_comparison_exp",
		id:"uuid_comparison_exp",
		nickname:"String_comparison_exp",
		transports:"String_comparison_exp",
		user:"users_bool_exp",
		userId:"uuid_comparison_exp"
	},
	authUserSecurityKeys_constraint: "enum" as const,
	authUserSecurityKeys_inc_input:{
		counter:"bigint"
	},
	authUserSecurityKeys_insert_input:{
		counter:"bigint",
		credentialPublicKey:"bytea",
		id:"uuid",
		user:"users_obj_rel_insert_input",
		userId:"uuid"
	},
	authUserSecurityKeys_max_order_by:{
		counter:"order_by",
		credentialId:"order_by",
		id:"order_by",
		nickname:"order_by",
		transports:"order_by",
		userId:"order_by"
	},
	authUserSecurityKeys_min_order_by:{
		counter:"order_by",
		credentialId:"order_by",
		id:"order_by",
		nickname:"order_by",
		transports:"order_by",
		userId:"order_by"
	},
	authUserSecurityKeys_on_conflict:{
		constraint:"authUserSecurityKeys_constraint",
		update_columns:"authUserSecurityKeys_update_column",
		where:"authUserSecurityKeys_bool_exp"
	},
	authUserSecurityKeys_order_by:{
		counter:"order_by",
		credentialId:"order_by",
		credentialPublicKey:"order_by",
		id:"order_by",
		nickname:"order_by",
		transports:"order_by",
		user:"users_order_by",
		userId:"order_by"
	},
	authUserSecurityKeys_pk_columns_input:{
		id:"uuid"
	},
	authUserSecurityKeys_select_column: "enum" as const,
	authUserSecurityKeys_set_input:{
		counter:"bigint",
		credentialPublicKey:"bytea",
		id:"uuid",
		userId:"uuid"
	},
	authUserSecurityKeys_stddev_order_by:{
		counter:"order_by"
	},
	authUserSecurityKeys_stddev_pop_order_by:{
		counter:"order_by"
	},
	authUserSecurityKeys_stddev_samp_order_by:{
		counter:"order_by"
	},
	authUserSecurityKeys_stream_cursor_input:{
		initial_value:"authUserSecurityKeys_stream_cursor_value_input",
		ordering:"cursor_ordering"
	},
	authUserSecurityKeys_stream_cursor_value_input:{
		counter:"bigint",
		credentialPublicKey:"bytea",
		id:"uuid",
		userId:"uuid"
	},
	authUserSecurityKeys_sum_order_by:{
		counter:"order_by"
	},
	authUserSecurityKeys_update_column: "enum" as const,
	authUserSecurityKeys_updates:{
		_inc:"authUserSecurityKeys_inc_input",
		_set:"authUserSecurityKeys_set_input",
		where:"authUserSecurityKeys_bool_exp"
	},
	authUserSecurityKeys_var_pop_order_by:{
		counter:"order_by"
	},
	authUserSecurityKeys_var_samp_order_by:{
		counter:"order_by"
	},
	authUserSecurityKeys_variance_order_by:{
		counter:"order_by"
	},
	beacon:{
		entity:{
			distinct_on:"entity_select_column",
			order_by:"entity_order_by",
			where:"entity_bool_exp"
		},
		entity_aggregate:{
			distinct_on:"entity_select_column",
			order_by:"entity_order_by",
			where:"entity_bool_exp"
		},
		meta:{

		},
		position_update:{
			distinct_on:"position_update_select_column",
			order_by:"position_update_order_by",
			where:"position_update_bool_exp"
		},
		position_update_aggregate:{
			distinct_on:"position_update_select_column",
			order_by:"position_update_order_by",
			where:"position_update_bool_exp"
		}
	},
	beacon_aggregate_fields:{
		count:{
			columns:"beacon_select_column"
		}
	},
	beacon_append_input:{
		meta:"jsonb"
	},
	beacon_bool_exp:{
		_and:"beacon_bool_exp",
		_not:"beacon_bool_exp",
		_or:"beacon_bool_exp",
		created_at:"timestamptz_comparison_exp",
		entity:"entity_bool_exp",
		entity_aggregate:"entity_aggregate_bool_exp",
		mac:"macaddr_comparison_exp",
		meta:"jsonb_comparison_exp",
		pk:"Int_comparison_exp",
		position_update:"position_update_bool_exp",
		position_update_aggregate:"position_update_aggregate_bool_exp",
		updated_at:"timestamptz_comparison_exp",
		uuid:"uuid_comparison_exp"
	},
	beacon_constraint: "enum" as const,
	beacon_delete_at_path_input:{

	},
	beacon_delete_elem_input:{

	},
	beacon_delete_key_input:{

	},
	beacon_insert_input:{
		created_at:"timestamptz",
		entity:"entity_arr_rel_insert_input",
		mac:"macaddr",
		meta:"jsonb",
		position_update:"position_update_arr_rel_insert_input",
		updated_at:"timestamptz",
		uuid:"uuid"
	},
	beacon_obj_rel_insert_input:{
		data:"beacon_insert_input",
		on_conflict:"beacon_on_conflict"
	},
	beacon_on_conflict:{
		constraint:"beacon_constraint",
		update_columns:"beacon_update_column",
		where:"beacon_bool_exp"
	},
	beacon_order_by:{
		created_at:"order_by",
		entity_aggregate:"entity_aggregate_order_by",
		mac:"order_by",
		meta:"order_by",
		pk:"order_by",
		position_update_aggregate:"position_update_aggregate_order_by",
		updated_at:"order_by",
		uuid:"order_by"
	},
	beacon_pk_columns_input:{

	},
	beacon_prepend_input:{
		meta:"jsonb"
	},
	beacon_select_column: "enum" as const,
	beacon_set_input:{
		created_at:"timestamptz",
		mac:"macaddr",
		meta:"jsonb",
		updated_at:"timestamptz",
		uuid:"uuid"
	},
	beacon_stream_cursor_input:{
		initial_value:"beacon_stream_cursor_value_input",
		ordering:"cursor_ordering"
	},
	beacon_stream_cursor_value_input:{
		created_at:"timestamptz",
		mac:"macaddr",
		meta:"jsonb",
		updated_at:"timestamptz",
		uuid:"uuid"
	},
	beacon_update_column: "enum" as const,
	beacon_updates:{
		_append:"beacon_append_input",
		_delete_at_path:"beacon_delete_at_path_input",
		_delete_elem:"beacon_delete_elem_input",
		_delete_key:"beacon_delete_key_input",
		_prepend:"beacon_prepend_input",
		_set:"beacon_set_input",
		where:"beacon_bool_exp"
	},
	bigint: `scalar.bigint` as const,
	bigint_comparison_exp:{
		_eq:"bigint",
		_gt:"bigint",
		_gte:"bigint",
		_in:"bigint",
		_lt:"bigint",
		_lte:"bigint",
		_neq:"bigint",
		_nin:"bigint"
	},
	buckets:{
		files:{
			distinct_on:"files_select_column",
			order_by:"files_order_by",
			where:"files_bool_exp"
		},
		files_aggregate:{
			distinct_on:"files_select_column",
			order_by:"files_order_by",
			where:"files_bool_exp"
		}
	},
	buckets_aggregate_fields:{
		count:{
			columns:"buckets_select_column"
		}
	},
	buckets_bool_exp:{
		_and:"buckets_bool_exp",
		_not:"buckets_bool_exp",
		_or:"buckets_bool_exp",
		cacheControl:"String_comparison_exp",
		createdAt:"timestamptz_comparison_exp",
		downloadExpiration:"Int_comparison_exp",
		files:"files_bool_exp",
		files_aggregate:"files_aggregate_bool_exp",
		id:"String_comparison_exp",
		maxUploadFileSize:"Int_comparison_exp",
		minUploadFileSize:"Int_comparison_exp",
		presignedUrlsEnabled:"Boolean_comparison_exp",
		updatedAt:"timestamptz_comparison_exp"
	},
	buckets_constraint: "enum" as const,
	buckets_inc_input:{

	},
	buckets_insert_input:{
		createdAt:"timestamptz",
		files:"files_arr_rel_insert_input",
		updatedAt:"timestamptz"
	},
	buckets_obj_rel_insert_input:{
		data:"buckets_insert_input",
		on_conflict:"buckets_on_conflict"
	},
	buckets_on_conflict:{
		constraint:"buckets_constraint",
		update_columns:"buckets_update_column",
		where:"buckets_bool_exp"
	},
	buckets_order_by:{
		cacheControl:"order_by",
		createdAt:"order_by",
		downloadExpiration:"order_by",
		files_aggregate:"files_aggregate_order_by",
		id:"order_by",
		maxUploadFileSize:"order_by",
		minUploadFileSize:"order_by",
		presignedUrlsEnabled:"order_by",
		updatedAt:"order_by"
	},
	buckets_pk_columns_input:{

	},
	buckets_select_column: "enum" as const,
	buckets_set_input:{
		createdAt:"timestamptz",
		updatedAt:"timestamptz"
	},
	buckets_stream_cursor_input:{
		initial_value:"buckets_stream_cursor_value_input",
		ordering:"cursor_ordering"
	},
	buckets_stream_cursor_value_input:{
		createdAt:"timestamptz",
		updatedAt:"timestamptz"
	},
	buckets_update_column: "enum" as const,
	buckets_updates:{
		_inc:"buckets_inc_input",
		_set:"buckets_set_input",
		where:"buckets_bool_exp"
	},
	bytea: `scalar.bytea` as const,
	bytea_comparison_exp:{
		_eq:"bytea",
		_gt:"bytea",
		_gte:"bytea",
		_in:"bytea",
		_lt:"bytea",
		_lte:"bytea",
		_neq:"bytea",
		_nin:"bytea"
	},
	citext: `scalar.citext` as const,
	citext_comparison_exp:{
		_eq:"citext",
		_gt:"citext",
		_gte:"citext",
		_ilike:"citext",
		_in:"citext",
		_iregex:"citext",
		_like:"citext",
		_lt:"citext",
		_lte:"citext",
		_neq:"citext",
		_nilike:"citext",
		_nin:"citext",
		_niregex:"citext",
		_nlike:"citext",
		_nregex:"citext",
		_nsimilar:"citext",
		_regex:"citext",
		_similar:"citext"
	},
	cursor_ordering: "enum" as const,
	entity:{
		data:{

		},
		meta:{

		},
		position_update:{
			distinct_on:"position_update_select_column",
			order_by:"position_update_order_by",
			where:"position_update_bool_exp"
		},
		position_update_aggregate:{
			distinct_on:"position_update_select_column",
			order_by:"position_update_order_by",
			where:"position_update_bool_exp"
		}
	},
	entity_aggregate_bool_exp:{
		count:"entity_aggregate_bool_exp_count"
	},
	entity_aggregate_bool_exp_count:{
		arguments:"entity_select_column",
		filter:"entity_bool_exp",
		predicate:"Int_comparison_exp"
	},
	entity_aggregate_fields:{
		count:{
			columns:"entity_select_column"
		}
	},
	entity_aggregate_order_by:{
		avg:"entity_avg_order_by",
		count:"order_by",
		max:"entity_max_order_by",
		min:"entity_min_order_by",
		stddev:"entity_stddev_order_by",
		stddev_pop:"entity_stddev_pop_order_by",
		stddev_samp:"entity_stddev_samp_order_by",
		sum:"entity_sum_order_by",
		var_pop:"entity_var_pop_order_by",
		var_samp:"entity_var_samp_order_by",
		variance:"entity_variance_order_by"
	},
	entity_append_input:{
		data:"jsonb",
		meta:"jsonb"
	},
	entity_arr_rel_insert_input:{
		data:"entity_insert_input",
		on_conflict:"entity_on_conflict"
	},
	entity_avg_order_by:{
		beacon_pk:"order_by",
		pk:"order_by"
	},
	entity_bool_exp:{
		_and:"entity_bool_exp",
		_not:"entity_bool_exp",
		_or:"entity_bool_exp",
		beacon:"beacon_bool_exp",
		beacon_pk:"Int_comparison_exp",
		data:"jsonb_comparison_exp",
		meta:"jsonb_comparison_exp",
		pk:"Int_comparison_exp",
		position_update:"position_update_bool_exp",
		position_update_aggregate:"position_update_aggregate_bool_exp",
		type:"String_comparison_exp",
		uuid:"uuid_comparison_exp"
	},
	entity_constraint: "enum" as const,
	entity_delete_at_path_input:{

	},
	entity_delete_elem_input:{

	},
	entity_delete_key_input:{

	},
	entity_inc_input:{

	},
	entity_insert_input:{
		beacon:"beacon_obj_rel_insert_input",
		data:"jsonb",
		meta:"jsonb",
		position_update:"position_update_arr_rel_insert_input",
		uuid:"uuid"
	},
	entity_max_order_by:{
		beacon_pk:"order_by",
		pk:"order_by",
		type:"order_by",
		uuid:"order_by"
	},
	entity_min_order_by:{
		beacon_pk:"order_by",
		pk:"order_by",
		type:"order_by",
		uuid:"order_by"
	},
	entity_obj_rel_insert_input:{
		data:"entity_insert_input",
		on_conflict:"entity_on_conflict"
	},
	entity_on_conflict:{
		constraint:"entity_constraint",
		update_columns:"entity_update_column",
		where:"entity_bool_exp"
	},
	entity_order_by:{
		beacon:"beacon_order_by",
		beacon_pk:"order_by",
		data:"order_by",
		meta:"order_by",
		pk:"order_by",
		position_update_aggregate:"position_update_aggregate_order_by",
		type:"order_by",
		uuid:"order_by"
	},
	entity_pk_columns_input:{

	},
	entity_prepend_input:{
		data:"jsonb",
		meta:"jsonb"
	},
	entity_select_column: "enum" as const,
	entity_set_input:{
		data:"jsonb",
		meta:"jsonb",
		uuid:"uuid"
	},
	entity_stddev_order_by:{
		beacon_pk:"order_by",
		pk:"order_by"
	},
	entity_stddev_pop_order_by:{
		beacon_pk:"order_by",
		pk:"order_by"
	},
	entity_stddev_samp_order_by:{
		beacon_pk:"order_by",
		pk:"order_by"
	},
	entity_stream_cursor_input:{
		initial_value:"entity_stream_cursor_value_input",
		ordering:"cursor_ordering"
	},
	entity_stream_cursor_value_input:{
		data:"jsonb",
		meta:"jsonb",
		uuid:"uuid"
	},
	entity_sum_order_by:{
		beacon_pk:"order_by",
		pk:"order_by"
	},
	entity_update_column: "enum" as const,
	entity_updates:{
		_append:"entity_append_input",
		_delete_at_path:"entity_delete_at_path_input",
		_delete_elem:"entity_delete_elem_input",
		_delete_key:"entity_delete_key_input",
		_inc:"entity_inc_input",
		_prepend:"entity_prepend_input",
		_set:"entity_set_input",
		where:"entity_bool_exp"
	},
	entity_var_pop_order_by:{
		beacon_pk:"order_by",
		pk:"order_by"
	},
	entity_var_samp_order_by:{
		beacon_pk:"order_by",
		pk:"order_by"
	},
	entity_variance_order_by:{
		beacon_pk:"order_by",
		pk:"order_by"
	},
	files_aggregate_bool_exp:{
		bool_and:"files_aggregate_bool_exp_bool_and",
		bool_or:"files_aggregate_bool_exp_bool_or",
		count:"files_aggregate_bool_exp_count"
	},
	files_aggregate_bool_exp_bool_and:{
		arguments:"files_select_column_files_aggregate_bool_exp_bool_and_arguments_columns",
		filter:"files_bool_exp",
		predicate:"Boolean_comparison_exp"
	},
	files_aggregate_bool_exp_bool_or:{
		arguments:"files_select_column_files_aggregate_bool_exp_bool_or_arguments_columns",
		filter:"files_bool_exp",
		predicate:"Boolean_comparison_exp"
	},
	files_aggregate_bool_exp_count:{
		arguments:"files_select_column",
		filter:"files_bool_exp",
		predicate:"Int_comparison_exp"
	},
	files_aggregate_fields:{
		count:{
			columns:"files_select_column"
		}
	},
	files_aggregate_order_by:{
		avg:"files_avg_order_by",
		count:"order_by",
		max:"files_max_order_by",
		min:"files_min_order_by",
		stddev:"files_stddev_order_by",
		stddev_pop:"files_stddev_pop_order_by",
		stddev_samp:"files_stddev_samp_order_by",
		sum:"files_sum_order_by",
		var_pop:"files_var_pop_order_by",
		var_samp:"files_var_samp_order_by",
		variance:"files_variance_order_by"
	},
	files_arr_rel_insert_input:{
		data:"files_insert_input",
		on_conflict:"files_on_conflict"
	},
	files_avg_order_by:{
		size:"order_by"
	},
	files_bool_exp:{
		_and:"files_bool_exp",
		_not:"files_bool_exp",
		_or:"files_bool_exp",
		bucket:"buckets_bool_exp",
		bucketId:"String_comparison_exp",
		createdAt:"timestamptz_comparison_exp",
		etag:"String_comparison_exp",
		id:"uuid_comparison_exp",
		isUploaded:"Boolean_comparison_exp",
		mimeType:"String_comparison_exp",
		name:"String_comparison_exp",
		size:"Int_comparison_exp",
		updatedAt:"timestamptz_comparison_exp",
		uploadedByUserId:"uuid_comparison_exp"
	},
	files_constraint: "enum" as const,
	files_inc_input:{

	},
	files_insert_input:{
		bucket:"buckets_obj_rel_insert_input",
		createdAt:"timestamptz",
		id:"uuid",
		updatedAt:"timestamptz",
		uploadedByUserId:"uuid"
	},
	files_max_order_by:{
		bucketId:"order_by",
		createdAt:"order_by",
		etag:"order_by",
		id:"order_by",
		mimeType:"order_by",
		name:"order_by",
		size:"order_by",
		updatedAt:"order_by",
		uploadedByUserId:"order_by"
	},
	files_min_order_by:{
		bucketId:"order_by",
		createdAt:"order_by",
		etag:"order_by",
		id:"order_by",
		mimeType:"order_by",
		name:"order_by",
		size:"order_by",
		updatedAt:"order_by",
		uploadedByUserId:"order_by"
	},
	files_on_conflict:{
		constraint:"files_constraint",
		update_columns:"files_update_column",
		where:"files_bool_exp"
	},
	files_order_by:{
		bucket:"buckets_order_by",
		bucketId:"order_by",
		createdAt:"order_by",
		etag:"order_by",
		id:"order_by",
		isUploaded:"order_by",
		mimeType:"order_by",
		name:"order_by",
		size:"order_by",
		updatedAt:"order_by",
		uploadedByUserId:"order_by"
	},
	files_pk_columns_input:{
		id:"uuid"
	},
	files_select_column: "enum" as const,
	files_select_column_files_aggregate_bool_exp_bool_and_arguments_columns: "enum" as const,
	files_select_column_files_aggregate_bool_exp_bool_or_arguments_columns: "enum" as const,
	files_set_input:{
		createdAt:"timestamptz",
		id:"uuid",
		updatedAt:"timestamptz",
		uploadedByUserId:"uuid"
	},
	files_stddev_order_by:{
		size:"order_by"
	},
	files_stddev_pop_order_by:{
		size:"order_by"
	},
	files_stddev_samp_order_by:{
		size:"order_by"
	},
	files_stream_cursor_input:{
		initial_value:"files_stream_cursor_value_input",
		ordering:"cursor_ordering"
	},
	files_stream_cursor_value_input:{
		createdAt:"timestamptz",
		id:"uuid",
		updatedAt:"timestamptz",
		uploadedByUserId:"uuid"
	},
	files_sum_order_by:{
		size:"order_by"
	},
	files_update_column: "enum" as const,
	files_updates:{
		_inc:"files_inc_input",
		_set:"files_set_input",
		where:"files_bool_exp"
	},
	files_var_pop_order_by:{
		size:"order_by"
	},
	files_var_samp_order_by:{
		size:"order_by"
	},
	files_variance_order_by:{
		size:"order_by"
	},
	jsonb: `scalar.jsonb` as const,
	jsonb_cast_exp:{
		String:"String_comparison_exp"
	},
	jsonb_comparison_exp:{
		_cast:"jsonb_cast_exp",
		_contained_in:"jsonb",
		_contains:"jsonb",
		_eq:"jsonb",
		_gt:"jsonb",
		_gte:"jsonb",
		_in:"jsonb",
		_lt:"jsonb",
		_lte:"jsonb",
		_neq:"jsonb",
		_nin:"jsonb"
	},
	macaddr: `scalar.macaddr` as const,
	macaddr_comparison_exp:{
		_eq:"macaddr",
		_gt:"macaddr",
		_gte:"macaddr",
		_in:"macaddr",
		_lt:"macaddr",
		_lte:"macaddr",
		_neq:"macaddr",
		_nin:"macaddr"
	},
	map:{
		floor_data:{

		},
		meta:{

		},
		position_update:{
			distinct_on:"position_update_select_column",
			order_by:"position_update_order_by",
			where:"position_update_bool_exp"
		},
		position_update_aggregate:{
			distinct_on:"position_update_select_column",
			order_by:"position_update_order_by",
			where:"position_update_bool_exp"
		}
	},
	map_aggregate_fields:{
		count:{
			columns:"map_select_column"
		}
	},
	map_append_input:{
		floor_data:"jsonb",
		meta:"jsonb"
	},
	map_bool_exp:{
		_and:"map_bool_exp",
		_not:"map_bool_exp",
		_or:"map_bool_exp",
		created_at:"timestamptz_comparison_exp",
		floor_data:"jsonb_comparison_exp",
		meta:"jsonb_comparison_exp",
		name:"String_comparison_exp",
		pk:"Int_comparison_exp",
		position_update:"position_update_bool_exp",
		position_update_aggregate:"position_update_aggregate_bool_exp",
		uuid:"uuid_comparison_exp"
	},
	map_constraint: "enum" as const,
	map_delete_at_path_input:{

	},
	map_delete_elem_input:{

	},
	map_delete_key_input:{

	},
	map_inc_input:{

	},
	map_insert_input:{
		created_at:"timestamptz",
		floor_data:"jsonb",
		meta:"jsonb",
		position_update:"position_update_arr_rel_insert_input",
		uuid:"uuid"
	},
	map_obj_rel_insert_input:{
		data:"map_insert_input",
		on_conflict:"map_on_conflict"
	},
	map_on_conflict:{
		constraint:"map_constraint",
		update_columns:"map_update_column",
		where:"map_bool_exp"
	},
	map_order_by:{
		created_at:"order_by",
		floor_data:"order_by",
		meta:"order_by",
		name:"order_by",
		pk:"order_by",
		position_update_aggregate:"position_update_aggregate_order_by",
		uuid:"order_by"
	},
	map_pk_columns_input:{

	},
	map_prepend_input:{
		floor_data:"jsonb",
		meta:"jsonb"
	},
	map_select_column: "enum" as const,
	map_set_input:{
		created_at:"timestamptz",
		floor_data:"jsonb",
		meta:"jsonb",
		uuid:"uuid"
	},
	map_stream_cursor_input:{
		initial_value:"map_stream_cursor_value_input",
		ordering:"cursor_ordering"
	},
	map_stream_cursor_value_input:{
		created_at:"timestamptz",
		floor_data:"jsonb",
		meta:"jsonb",
		uuid:"uuid"
	},
	map_update_column: "enum" as const,
	map_updates:{
		_append:"map_append_input",
		_delete_at_path:"map_delete_at_path_input",
		_delete_elem:"map_delete_elem_input",
		_delete_key:"map_delete_key_input",
		_inc:"map_inc_input",
		_prepend:"map_prepend_input",
		_set:"map_set_input",
		where:"map_bool_exp"
	},
	mutation_root:{
		deleteAuthProvider:{

		},
		deleteAuthProviderRequest:{
			id:"uuid"
		},
		deleteAuthProviderRequests:{
			where:"authProviderRequests_bool_exp"
		},
		deleteAuthProviders:{
			where:"authProviders_bool_exp"
		},
		deleteAuthRefreshToken:{
			refreshToken:"uuid"
		},
		deleteAuthRefreshTokens:{
			where:"authRefreshTokens_bool_exp"
		},
		deleteAuthRole:{

		},
		deleteAuthRoles:{
			where:"authRoles_bool_exp"
		},
		deleteAuthUserProvider:{
			id:"uuid"
		},
		deleteAuthUserProviders:{
			where:"authUserProviders_bool_exp"
		},
		deleteAuthUserRole:{
			id:"uuid"
		},
		deleteAuthUserRoles:{
			where:"authUserRoles_bool_exp"
		},
		deleteAuthUserSecurityKey:{
			id:"uuid"
		},
		deleteAuthUserSecurityKeys:{
			where:"authUserSecurityKeys_bool_exp"
		},
		deleteBucket:{

		},
		deleteBuckets:{
			where:"buckets_bool_exp"
		},
		deleteFile:{
			id:"uuid"
		},
		deleteFiles:{
			where:"files_bool_exp"
		},
		deleteUser:{
			id:"uuid"
		},
		deleteUsers:{
			where:"users_bool_exp"
		},
		delete_beacon:{
			where:"beacon_bool_exp"
		},
		delete_beacon_by_pk:{

		},
		delete_entity:{
			where:"entity_bool_exp"
		},
		delete_entity_by_pk:{

		},
		delete_map:{
			where:"map_bool_exp"
		},
		delete_map_by_pk:{

		},
		delete_position_update:{
			where:"position_update_bool_exp"
		},
		delete_position_update_by_pk:{

		},
		insertAuthProvider:{
			object:"authProviders_insert_input",
			on_conflict:"authProviders_on_conflict"
		},
		insertAuthProviderRequest:{
			object:"authProviderRequests_insert_input",
			on_conflict:"authProviderRequests_on_conflict"
		},
		insertAuthProviderRequests:{
			objects:"authProviderRequests_insert_input",
			on_conflict:"authProviderRequests_on_conflict"
		},
		insertAuthProviders:{
			objects:"authProviders_insert_input",
			on_conflict:"authProviders_on_conflict"
		},
		insertAuthRefreshToken:{
			object:"authRefreshTokens_insert_input",
			on_conflict:"authRefreshTokens_on_conflict"
		},
		insertAuthRefreshTokens:{
			objects:"authRefreshTokens_insert_input",
			on_conflict:"authRefreshTokens_on_conflict"
		},
		insertAuthRole:{
			object:"authRoles_insert_input",
			on_conflict:"authRoles_on_conflict"
		},
		insertAuthRoles:{
			objects:"authRoles_insert_input",
			on_conflict:"authRoles_on_conflict"
		},
		insertAuthUserProvider:{
			object:"authUserProviders_insert_input",
			on_conflict:"authUserProviders_on_conflict"
		},
		insertAuthUserProviders:{
			objects:"authUserProviders_insert_input",
			on_conflict:"authUserProviders_on_conflict"
		},
		insertAuthUserRole:{
			object:"authUserRoles_insert_input",
			on_conflict:"authUserRoles_on_conflict"
		},
		insertAuthUserRoles:{
			objects:"authUserRoles_insert_input",
			on_conflict:"authUserRoles_on_conflict"
		},
		insertAuthUserSecurityKey:{
			object:"authUserSecurityKeys_insert_input",
			on_conflict:"authUserSecurityKeys_on_conflict"
		},
		insertAuthUserSecurityKeys:{
			objects:"authUserSecurityKeys_insert_input",
			on_conflict:"authUserSecurityKeys_on_conflict"
		},
		insertBucket:{
			object:"buckets_insert_input",
			on_conflict:"buckets_on_conflict"
		},
		insertBuckets:{
			objects:"buckets_insert_input",
			on_conflict:"buckets_on_conflict"
		},
		insertFile:{
			object:"files_insert_input",
			on_conflict:"files_on_conflict"
		},
		insertFiles:{
			objects:"files_insert_input",
			on_conflict:"files_on_conflict"
		},
		insertUser:{
			object:"users_insert_input",
			on_conflict:"users_on_conflict"
		},
		insertUsers:{
			objects:"users_insert_input",
			on_conflict:"users_on_conflict"
		},
		insert_beacon:{
			objects:"beacon_insert_input",
			on_conflict:"beacon_on_conflict"
		},
		insert_beacon_one:{
			object:"beacon_insert_input",
			on_conflict:"beacon_on_conflict"
		},
		insert_entity:{
			objects:"entity_insert_input",
			on_conflict:"entity_on_conflict"
		},
		insert_entity_one:{
			object:"entity_insert_input",
			on_conflict:"entity_on_conflict"
		},
		insert_map:{
			objects:"map_insert_input",
			on_conflict:"map_on_conflict"
		},
		insert_map_one:{
			object:"map_insert_input",
			on_conflict:"map_on_conflict"
		},
		insert_position_update:{
			objects:"position_update_insert_input",
			on_conflict:"position_update_on_conflict"
		},
		insert_position_update_one:{
			object:"position_update_insert_input",
			on_conflict:"position_update_on_conflict"
		},
		updateAuthProvider:{
			_set:"authProviders_set_input",
			pk_columns:"authProviders_pk_columns_input"
		},
		updateAuthProviderRequest:{
			_append:"authProviderRequests_append_input",
			_delete_at_path:"authProviderRequests_delete_at_path_input",
			_delete_elem:"authProviderRequests_delete_elem_input",
			_delete_key:"authProviderRequests_delete_key_input",
			_prepend:"authProviderRequests_prepend_input",
			_set:"authProviderRequests_set_input",
			pk_columns:"authProviderRequests_pk_columns_input"
		},
		updateAuthProviderRequests:{
			_append:"authProviderRequests_append_input",
			_delete_at_path:"authProviderRequests_delete_at_path_input",
			_delete_elem:"authProviderRequests_delete_elem_input",
			_delete_key:"authProviderRequests_delete_key_input",
			_prepend:"authProviderRequests_prepend_input",
			_set:"authProviderRequests_set_input",
			where:"authProviderRequests_bool_exp"
		},
		updateAuthProviders:{
			_set:"authProviders_set_input",
			where:"authProviders_bool_exp"
		},
		updateAuthRefreshToken:{
			_set:"authRefreshTokens_set_input",
			pk_columns:"authRefreshTokens_pk_columns_input"
		},
		updateAuthRefreshTokens:{
			_set:"authRefreshTokens_set_input",
			where:"authRefreshTokens_bool_exp"
		},
		updateAuthRole:{
			_set:"authRoles_set_input",
			pk_columns:"authRoles_pk_columns_input"
		},
		updateAuthRoles:{
			_set:"authRoles_set_input",
			where:"authRoles_bool_exp"
		},
		updateAuthUserProvider:{
			_set:"authUserProviders_set_input",
			pk_columns:"authUserProviders_pk_columns_input"
		},
		updateAuthUserProviders:{
			_set:"authUserProviders_set_input",
			where:"authUserProviders_bool_exp"
		},
		updateAuthUserRole:{
			_set:"authUserRoles_set_input",
			pk_columns:"authUserRoles_pk_columns_input"
		},
		updateAuthUserRoles:{
			_set:"authUserRoles_set_input",
			where:"authUserRoles_bool_exp"
		},
		updateAuthUserSecurityKey:{
			_inc:"authUserSecurityKeys_inc_input",
			_set:"authUserSecurityKeys_set_input",
			pk_columns:"authUserSecurityKeys_pk_columns_input"
		},
		updateAuthUserSecurityKeys:{
			_inc:"authUserSecurityKeys_inc_input",
			_set:"authUserSecurityKeys_set_input",
			where:"authUserSecurityKeys_bool_exp"
		},
		updateBucket:{
			_inc:"buckets_inc_input",
			_set:"buckets_set_input",
			pk_columns:"buckets_pk_columns_input"
		},
		updateBuckets:{
			_inc:"buckets_inc_input",
			_set:"buckets_set_input",
			where:"buckets_bool_exp"
		},
		updateFile:{
			_inc:"files_inc_input",
			_set:"files_set_input",
			pk_columns:"files_pk_columns_input"
		},
		updateFiles:{
			_inc:"files_inc_input",
			_set:"files_set_input",
			where:"files_bool_exp"
		},
		updateUser:{
			_append:"users_append_input",
			_delete_at_path:"users_delete_at_path_input",
			_delete_elem:"users_delete_elem_input",
			_delete_key:"users_delete_key_input",
			_prepend:"users_prepend_input",
			_set:"users_set_input",
			pk_columns:"users_pk_columns_input"
		},
		updateUsers:{
			_append:"users_append_input",
			_delete_at_path:"users_delete_at_path_input",
			_delete_elem:"users_delete_elem_input",
			_delete_key:"users_delete_key_input",
			_prepend:"users_prepend_input",
			_set:"users_set_input",
			where:"users_bool_exp"
		},
		update_authProviderRequests_many:{
			updates:"authProviderRequests_updates"
		},
		update_authProviders_many:{
			updates:"authProviders_updates"
		},
		update_authRefreshTokens_many:{
			updates:"authRefreshTokens_updates"
		},
		update_authRoles_many:{
			updates:"authRoles_updates"
		},
		update_authUserProviders_many:{
			updates:"authUserProviders_updates"
		},
		update_authUserRoles_many:{
			updates:"authUserRoles_updates"
		},
		update_authUserSecurityKeys_many:{
			updates:"authUserSecurityKeys_updates"
		},
		update_beacon:{
			_append:"beacon_append_input",
			_delete_at_path:"beacon_delete_at_path_input",
			_delete_elem:"beacon_delete_elem_input",
			_delete_key:"beacon_delete_key_input",
			_prepend:"beacon_prepend_input",
			_set:"beacon_set_input",
			where:"beacon_bool_exp"
		},
		update_beacon_by_pk:{
			_append:"beacon_append_input",
			_delete_at_path:"beacon_delete_at_path_input",
			_delete_elem:"beacon_delete_elem_input",
			_delete_key:"beacon_delete_key_input",
			_prepend:"beacon_prepend_input",
			_set:"beacon_set_input",
			pk_columns:"beacon_pk_columns_input"
		},
		update_beacon_many:{
			updates:"beacon_updates"
		},
		update_buckets_many:{
			updates:"buckets_updates"
		},
		update_entity:{
			_append:"entity_append_input",
			_delete_at_path:"entity_delete_at_path_input",
			_delete_elem:"entity_delete_elem_input",
			_delete_key:"entity_delete_key_input",
			_inc:"entity_inc_input",
			_prepend:"entity_prepend_input",
			_set:"entity_set_input",
			where:"entity_bool_exp"
		},
		update_entity_by_pk:{
			_append:"entity_append_input",
			_delete_at_path:"entity_delete_at_path_input",
			_delete_elem:"entity_delete_elem_input",
			_delete_key:"entity_delete_key_input",
			_inc:"entity_inc_input",
			_prepend:"entity_prepend_input",
			_set:"entity_set_input",
			pk_columns:"entity_pk_columns_input"
		},
		update_entity_many:{
			updates:"entity_updates"
		},
		update_files_many:{
			updates:"files_updates"
		},
		update_map:{
			_append:"map_append_input",
			_delete_at_path:"map_delete_at_path_input",
			_delete_elem:"map_delete_elem_input",
			_delete_key:"map_delete_key_input",
			_inc:"map_inc_input",
			_prepend:"map_prepend_input",
			_set:"map_set_input",
			where:"map_bool_exp"
		},
		update_map_by_pk:{
			_append:"map_append_input",
			_delete_at_path:"map_delete_at_path_input",
			_delete_elem:"map_delete_elem_input",
			_delete_key:"map_delete_key_input",
			_inc:"map_inc_input",
			_prepend:"map_prepend_input",
			_set:"map_set_input",
			pk_columns:"map_pk_columns_input"
		},
		update_map_many:{
			updates:"map_updates"
		},
		update_position_update:{
			_inc:"position_update_inc_input",
			_set:"position_update_set_input",
			where:"position_update_bool_exp"
		},
		update_position_update_by_pk:{
			_inc:"position_update_inc_input",
			_set:"position_update_set_input",
			pk_columns:"position_update_pk_columns_input"
		},
		update_position_update_many:{
			updates:"position_update_updates"
		},
		update_users_many:{
			updates:"users_updates"
		}
	},
	order_by: "enum" as const,
	position_update_aggregate_bool_exp:{
		count:"position_update_aggregate_bool_exp_count"
	},
	position_update_aggregate_bool_exp_count:{
		arguments:"position_update_select_column",
		filter:"position_update_bool_exp",
		predicate:"Int_comparison_exp"
	},
	position_update_aggregate_fields:{
		count:{
			columns:"position_update_select_column"
		}
	},
	position_update_aggregate_order_by:{
		avg:"position_update_avg_order_by",
		count:"order_by",
		max:"position_update_max_order_by",
		min:"position_update_min_order_by",
		stddev:"position_update_stddev_order_by",
		stddev_pop:"position_update_stddev_pop_order_by",
		stddev_samp:"position_update_stddev_samp_order_by",
		sum:"position_update_sum_order_by",
		var_pop:"position_update_var_pop_order_by",
		var_samp:"position_update_var_samp_order_by",
		variance:"position_update_variance_order_by"
	},
	position_update_arr_rel_insert_input:{
		data:"position_update_insert_input",
		on_conflict:"position_update_on_conflict"
	},
	position_update_avg_order_by:{
		beacon_pk:"order_by",
		entity_pk:"order_by",
		map_pk:"order_by",
		pk:"order_by",
		x:"order_by",
		y:"order_by"
	},
	position_update_bool_exp:{
		_and:"position_update_bool_exp",
		_not:"position_update_bool_exp",
		_or:"position_update_bool_exp",
		beacon:"beacon_bool_exp",
		beacon_pk:"Int_comparison_exp",
		created_at:"timestamptz_comparison_exp",
		entity:"entity_bool_exp",
		entity_pk:"Int_comparison_exp",
		map:"map_bool_exp",
		map_pk:"Int_comparison_exp",
		pk:"Int_comparison_exp",
		x:"Float_comparison_exp",
		y:"Float_comparison_exp"
	},
	position_update_constraint: "enum" as const,
	position_update_inc_input:{

	},
	position_update_insert_input:{
		beacon:"beacon_obj_rel_insert_input",
		created_at:"timestamptz",
		entity:"entity_obj_rel_insert_input",
		map:"map_obj_rel_insert_input"
	},
	position_update_max_order_by:{
		beacon_pk:"order_by",
		created_at:"order_by",
		entity_pk:"order_by",
		map_pk:"order_by",
		pk:"order_by",
		x:"order_by",
		y:"order_by"
	},
	position_update_min_order_by:{
		beacon_pk:"order_by",
		created_at:"order_by",
		entity_pk:"order_by",
		map_pk:"order_by",
		pk:"order_by",
		x:"order_by",
		y:"order_by"
	},
	position_update_on_conflict:{
		constraint:"position_update_constraint",
		update_columns:"position_update_update_column",
		where:"position_update_bool_exp"
	},
	position_update_order_by:{
		beacon:"beacon_order_by",
		beacon_pk:"order_by",
		created_at:"order_by",
		entity:"entity_order_by",
		entity_pk:"order_by",
		map:"map_order_by",
		map_pk:"order_by",
		pk:"order_by",
		x:"order_by",
		y:"order_by"
	},
	position_update_pk_columns_input:{

	},
	position_update_select_column: "enum" as const,
	position_update_set_input:{
		created_at:"timestamptz"
	},
	position_update_stddev_order_by:{
		beacon_pk:"order_by",
		entity_pk:"order_by",
		map_pk:"order_by",
		pk:"order_by",
		x:"order_by",
		y:"order_by"
	},
	position_update_stddev_pop_order_by:{
		beacon_pk:"order_by",
		entity_pk:"order_by",
		map_pk:"order_by",
		pk:"order_by",
		x:"order_by",
		y:"order_by"
	},
	position_update_stddev_samp_order_by:{
		beacon_pk:"order_by",
		entity_pk:"order_by",
		map_pk:"order_by",
		pk:"order_by",
		x:"order_by",
		y:"order_by"
	},
	position_update_stream_cursor_input:{
		initial_value:"position_update_stream_cursor_value_input",
		ordering:"cursor_ordering"
	},
	position_update_stream_cursor_value_input:{
		created_at:"timestamptz"
	},
	position_update_sum_order_by:{
		beacon_pk:"order_by",
		entity_pk:"order_by",
		map_pk:"order_by",
		pk:"order_by",
		x:"order_by",
		y:"order_by"
	},
	position_update_update_column: "enum" as const,
	position_update_updates:{
		_inc:"position_update_inc_input",
		_set:"position_update_set_input",
		where:"position_update_bool_exp"
	},
	position_update_var_pop_order_by:{
		beacon_pk:"order_by",
		entity_pk:"order_by",
		map_pk:"order_by",
		pk:"order_by",
		x:"order_by",
		y:"order_by"
	},
	position_update_var_samp_order_by:{
		beacon_pk:"order_by",
		entity_pk:"order_by",
		map_pk:"order_by",
		pk:"order_by",
		x:"order_by",
		y:"order_by"
	},
	position_update_variance_order_by:{
		beacon_pk:"order_by",
		entity_pk:"order_by",
		map_pk:"order_by",
		pk:"order_by",
		x:"order_by",
		y:"order_by"
	},
	query_root:{
		authProvider:{

		},
		authProviderRequest:{
			id:"uuid"
		},
		authProviderRequests:{
			distinct_on:"authProviderRequests_select_column",
			order_by:"authProviderRequests_order_by",
			where:"authProviderRequests_bool_exp"
		},
		authProviderRequestsAggregate:{
			distinct_on:"authProviderRequests_select_column",
			order_by:"authProviderRequests_order_by",
			where:"authProviderRequests_bool_exp"
		},
		authProviders:{
			distinct_on:"authProviders_select_column",
			order_by:"authProviders_order_by",
			where:"authProviders_bool_exp"
		},
		authProvidersAggregate:{
			distinct_on:"authProviders_select_column",
			order_by:"authProviders_order_by",
			where:"authProviders_bool_exp"
		},
		authRefreshToken:{
			refreshToken:"uuid"
		},
		authRefreshTokens:{
			distinct_on:"authRefreshTokens_select_column",
			order_by:"authRefreshTokens_order_by",
			where:"authRefreshTokens_bool_exp"
		},
		authRefreshTokensAggregate:{
			distinct_on:"authRefreshTokens_select_column",
			order_by:"authRefreshTokens_order_by",
			where:"authRefreshTokens_bool_exp"
		},
		authRole:{

		},
		authRoles:{
			distinct_on:"authRoles_select_column",
			order_by:"authRoles_order_by",
			where:"authRoles_bool_exp"
		},
		authRolesAggregate:{
			distinct_on:"authRoles_select_column",
			order_by:"authRoles_order_by",
			where:"authRoles_bool_exp"
		},
		authUserProvider:{
			id:"uuid"
		},
		authUserProviders:{
			distinct_on:"authUserProviders_select_column",
			order_by:"authUserProviders_order_by",
			where:"authUserProviders_bool_exp"
		},
		authUserProvidersAggregate:{
			distinct_on:"authUserProviders_select_column",
			order_by:"authUserProviders_order_by",
			where:"authUserProviders_bool_exp"
		},
		authUserRole:{
			id:"uuid"
		},
		authUserRoles:{
			distinct_on:"authUserRoles_select_column",
			order_by:"authUserRoles_order_by",
			where:"authUserRoles_bool_exp"
		},
		authUserRolesAggregate:{
			distinct_on:"authUserRoles_select_column",
			order_by:"authUserRoles_order_by",
			where:"authUserRoles_bool_exp"
		},
		authUserSecurityKey:{
			id:"uuid"
		},
		authUserSecurityKeys:{
			distinct_on:"authUserSecurityKeys_select_column",
			order_by:"authUserSecurityKeys_order_by",
			where:"authUserSecurityKeys_bool_exp"
		},
		authUserSecurityKeysAggregate:{
			distinct_on:"authUserSecurityKeys_select_column",
			order_by:"authUserSecurityKeys_order_by",
			where:"authUserSecurityKeys_bool_exp"
		},
		beacon:{
			distinct_on:"beacon_select_column",
			order_by:"beacon_order_by",
			where:"beacon_bool_exp"
		},
		beacon_aggregate:{
			distinct_on:"beacon_select_column",
			order_by:"beacon_order_by",
			where:"beacon_bool_exp"
		},
		beacon_by_pk:{

		},
		bucket:{

		},
		buckets:{
			distinct_on:"buckets_select_column",
			order_by:"buckets_order_by",
			where:"buckets_bool_exp"
		},
		bucketsAggregate:{
			distinct_on:"buckets_select_column",
			order_by:"buckets_order_by",
			where:"buckets_bool_exp"
		},
		entity:{
			distinct_on:"entity_select_column",
			order_by:"entity_order_by",
			where:"entity_bool_exp"
		},
		entity_aggregate:{
			distinct_on:"entity_select_column",
			order_by:"entity_order_by",
			where:"entity_bool_exp"
		},
		entity_by_pk:{

		},
		file:{
			id:"uuid"
		},
		files:{
			distinct_on:"files_select_column",
			order_by:"files_order_by",
			where:"files_bool_exp"
		},
		filesAggregate:{
			distinct_on:"files_select_column",
			order_by:"files_order_by",
			where:"files_bool_exp"
		},
		map:{
			distinct_on:"map_select_column",
			order_by:"map_order_by",
			where:"map_bool_exp"
		},
		map_aggregate:{
			distinct_on:"map_select_column",
			order_by:"map_order_by",
			where:"map_bool_exp"
		},
		map_by_pk:{

		},
		position_update:{
			distinct_on:"position_update_select_column",
			order_by:"position_update_order_by",
			where:"position_update_bool_exp"
		},
		position_update_aggregate:{
			distinct_on:"position_update_select_column",
			order_by:"position_update_order_by",
			where:"position_update_bool_exp"
		},
		position_update_by_pk:{

		},
		user:{
			id:"uuid"
		},
		users:{
			distinct_on:"users_select_column",
			order_by:"users_order_by",
			where:"users_bool_exp"
		},
		usersAggregate:{
			distinct_on:"users_select_column",
			order_by:"users_order_by",
			where:"users_bool_exp"
		}
	},
	subscription_root:{
		authProvider:{

		},
		authProviderRequest:{
			id:"uuid"
		},
		authProviderRequests:{
			distinct_on:"authProviderRequests_select_column",
			order_by:"authProviderRequests_order_by",
			where:"authProviderRequests_bool_exp"
		},
		authProviderRequestsAggregate:{
			distinct_on:"authProviderRequests_select_column",
			order_by:"authProviderRequests_order_by",
			where:"authProviderRequests_bool_exp"
		},
		authProviderRequests_stream:{
			cursor:"authProviderRequests_stream_cursor_input",
			where:"authProviderRequests_bool_exp"
		},
		authProviders:{
			distinct_on:"authProviders_select_column",
			order_by:"authProviders_order_by",
			where:"authProviders_bool_exp"
		},
		authProvidersAggregate:{
			distinct_on:"authProviders_select_column",
			order_by:"authProviders_order_by",
			where:"authProviders_bool_exp"
		},
		authProviders_stream:{
			cursor:"authProviders_stream_cursor_input",
			where:"authProviders_bool_exp"
		},
		authRefreshToken:{
			refreshToken:"uuid"
		},
		authRefreshTokens:{
			distinct_on:"authRefreshTokens_select_column",
			order_by:"authRefreshTokens_order_by",
			where:"authRefreshTokens_bool_exp"
		},
		authRefreshTokensAggregate:{
			distinct_on:"authRefreshTokens_select_column",
			order_by:"authRefreshTokens_order_by",
			where:"authRefreshTokens_bool_exp"
		},
		authRefreshTokens_stream:{
			cursor:"authRefreshTokens_stream_cursor_input",
			where:"authRefreshTokens_bool_exp"
		},
		authRole:{

		},
		authRoles:{
			distinct_on:"authRoles_select_column",
			order_by:"authRoles_order_by",
			where:"authRoles_bool_exp"
		},
		authRolesAggregate:{
			distinct_on:"authRoles_select_column",
			order_by:"authRoles_order_by",
			where:"authRoles_bool_exp"
		},
		authRoles_stream:{
			cursor:"authRoles_stream_cursor_input",
			where:"authRoles_bool_exp"
		},
		authUserProvider:{
			id:"uuid"
		},
		authUserProviders:{
			distinct_on:"authUserProviders_select_column",
			order_by:"authUserProviders_order_by",
			where:"authUserProviders_bool_exp"
		},
		authUserProvidersAggregate:{
			distinct_on:"authUserProviders_select_column",
			order_by:"authUserProviders_order_by",
			where:"authUserProviders_bool_exp"
		},
		authUserProviders_stream:{
			cursor:"authUserProviders_stream_cursor_input",
			where:"authUserProviders_bool_exp"
		},
		authUserRole:{
			id:"uuid"
		},
		authUserRoles:{
			distinct_on:"authUserRoles_select_column",
			order_by:"authUserRoles_order_by",
			where:"authUserRoles_bool_exp"
		},
		authUserRolesAggregate:{
			distinct_on:"authUserRoles_select_column",
			order_by:"authUserRoles_order_by",
			where:"authUserRoles_bool_exp"
		},
		authUserRoles_stream:{
			cursor:"authUserRoles_stream_cursor_input",
			where:"authUserRoles_bool_exp"
		},
		authUserSecurityKey:{
			id:"uuid"
		},
		authUserSecurityKeys:{
			distinct_on:"authUserSecurityKeys_select_column",
			order_by:"authUserSecurityKeys_order_by",
			where:"authUserSecurityKeys_bool_exp"
		},
		authUserSecurityKeysAggregate:{
			distinct_on:"authUserSecurityKeys_select_column",
			order_by:"authUserSecurityKeys_order_by",
			where:"authUserSecurityKeys_bool_exp"
		},
		authUserSecurityKeys_stream:{
			cursor:"authUserSecurityKeys_stream_cursor_input",
			where:"authUserSecurityKeys_bool_exp"
		},
		beacon:{
			distinct_on:"beacon_select_column",
			order_by:"beacon_order_by",
			where:"beacon_bool_exp"
		},
		beacon_aggregate:{
			distinct_on:"beacon_select_column",
			order_by:"beacon_order_by",
			where:"beacon_bool_exp"
		},
		beacon_by_pk:{

		},
		beacon_stream:{
			cursor:"beacon_stream_cursor_input",
			where:"beacon_bool_exp"
		},
		bucket:{

		},
		buckets:{
			distinct_on:"buckets_select_column",
			order_by:"buckets_order_by",
			where:"buckets_bool_exp"
		},
		bucketsAggregate:{
			distinct_on:"buckets_select_column",
			order_by:"buckets_order_by",
			where:"buckets_bool_exp"
		},
		buckets_stream:{
			cursor:"buckets_stream_cursor_input",
			where:"buckets_bool_exp"
		},
		entity:{
			distinct_on:"entity_select_column",
			order_by:"entity_order_by",
			where:"entity_bool_exp"
		},
		entity_aggregate:{
			distinct_on:"entity_select_column",
			order_by:"entity_order_by",
			where:"entity_bool_exp"
		},
		entity_by_pk:{

		},
		entity_stream:{
			cursor:"entity_stream_cursor_input",
			where:"entity_bool_exp"
		},
		file:{
			id:"uuid"
		},
		files:{
			distinct_on:"files_select_column",
			order_by:"files_order_by",
			where:"files_bool_exp"
		},
		filesAggregate:{
			distinct_on:"files_select_column",
			order_by:"files_order_by",
			where:"files_bool_exp"
		},
		files_stream:{
			cursor:"files_stream_cursor_input",
			where:"files_bool_exp"
		},
		map:{
			distinct_on:"map_select_column",
			order_by:"map_order_by",
			where:"map_bool_exp"
		},
		map_aggregate:{
			distinct_on:"map_select_column",
			order_by:"map_order_by",
			where:"map_bool_exp"
		},
		map_by_pk:{

		},
		map_stream:{
			cursor:"map_stream_cursor_input",
			where:"map_bool_exp"
		},
		position_update:{
			distinct_on:"position_update_select_column",
			order_by:"position_update_order_by",
			where:"position_update_bool_exp"
		},
		position_update_aggregate:{
			distinct_on:"position_update_select_column",
			order_by:"position_update_order_by",
			where:"position_update_bool_exp"
		},
		position_update_by_pk:{

		},
		position_update_stream:{
			cursor:"position_update_stream_cursor_input",
			where:"position_update_bool_exp"
		},
		user:{
			id:"uuid"
		},
		users:{
			distinct_on:"users_select_column",
			order_by:"users_order_by",
			where:"users_bool_exp"
		},
		usersAggregate:{
			distinct_on:"users_select_column",
			order_by:"users_order_by",
			where:"users_bool_exp"
		},
		users_stream:{
			cursor:"users_stream_cursor_input",
			where:"users_bool_exp"
		}
	},
	timestamptz: `scalar.timestamptz` as const,
	timestamptz_comparison_exp:{
		_eq:"timestamptz",
		_gt:"timestamptz",
		_gte:"timestamptz",
		_in:"timestamptz",
		_lt:"timestamptz",
		_lte:"timestamptz",
		_neq:"timestamptz",
		_nin:"timestamptz"
	},
	users:{
		metadata:{

		},
		refreshTokens:{
			distinct_on:"authRefreshTokens_select_column",
			order_by:"authRefreshTokens_order_by",
			where:"authRefreshTokens_bool_exp"
		},
		refreshTokens_aggregate:{
			distinct_on:"authRefreshTokens_select_column",
			order_by:"authRefreshTokens_order_by",
			where:"authRefreshTokens_bool_exp"
		},
		roles:{
			distinct_on:"authUserRoles_select_column",
			order_by:"authUserRoles_order_by",
			where:"authUserRoles_bool_exp"
		},
		roles_aggregate:{
			distinct_on:"authUserRoles_select_column",
			order_by:"authUserRoles_order_by",
			where:"authUserRoles_bool_exp"
		},
		securityKeys:{
			distinct_on:"authUserSecurityKeys_select_column",
			order_by:"authUserSecurityKeys_order_by",
			where:"authUserSecurityKeys_bool_exp"
		},
		securityKeys_aggregate:{
			distinct_on:"authUserSecurityKeys_select_column",
			order_by:"authUserSecurityKeys_order_by",
			where:"authUserSecurityKeys_bool_exp"
		},
		userProviders:{
			distinct_on:"authUserProviders_select_column",
			order_by:"authUserProviders_order_by",
			where:"authUserProviders_bool_exp"
		},
		userProviders_aggregate:{
			distinct_on:"authUserProviders_select_column",
			order_by:"authUserProviders_order_by",
			where:"authUserProviders_bool_exp"
		}
	},
	users_aggregate_bool_exp:{
		bool_and:"users_aggregate_bool_exp_bool_and",
		bool_or:"users_aggregate_bool_exp_bool_or",
		count:"users_aggregate_bool_exp_count"
	},
	users_aggregate_bool_exp_bool_and:{
		arguments:"users_select_column_users_aggregate_bool_exp_bool_and_arguments_columns",
		filter:"users_bool_exp",
		predicate:"Boolean_comparison_exp"
	},
	users_aggregate_bool_exp_bool_or:{
		arguments:"users_select_column_users_aggregate_bool_exp_bool_or_arguments_columns",
		filter:"users_bool_exp",
		predicate:"Boolean_comparison_exp"
	},
	users_aggregate_bool_exp_count:{
		arguments:"users_select_column",
		filter:"users_bool_exp",
		predicate:"Int_comparison_exp"
	},
	users_aggregate_fields:{
		count:{
			columns:"users_select_column"
		}
	},
	users_aggregate_order_by:{
		count:"order_by",
		max:"users_max_order_by",
		min:"users_min_order_by"
	},
	users_append_input:{
		metadata:"jsonb"
	},
	users_arr_rel_insert_input:{
		data:"users_insert_input",
		on_conflict:"users_on_conflict"
	},
	users_bool_exp:{
		_and:"users_bool_exp",
		_not:"users_bool_exp",
		_or:"users_bool_exp",
		activeMfaType:"String_comparison_exp",
		avatarUrl:"String_comparison_exp",
		createdAt:"timestamptz_comparison_exp",
		currentChallenge:"String_comparison_exp",
		defaultRole:"String_comparison_exp",
		defaultRoleByRole:"authRoles_bool_exp",
		disabled:"Boolean_comparison_exp",
		displayName:"String_comparison_exp",
		email:"citext_comparison_exp",
		emailVerified:"Boolean_comparison_exp",
		id:"uuid_comparison_exp",
		isAnonymous:"Boolean_comparison_exp",
		lastSeen:"timestamptz_comparison_exp",
		locale:"String_comparison_exp",
		metadata:"jsonb_comparison_exp",
		newEmail:"citext_comparison_exp",
		otpHash:"String_comparison_exp",
		otpHashExpiresAt:"timestamptz_comparison_exp",
		otpMethodLastUsed:"String_comparison_exp",
		passwordHash:"String_comparison_exp",
		phoneNumber:"String_comparison_exp",
		phoneNumberVerified:"Boolean_comparison_exp",
		refreshTokens:"authRefreshTokens_bool_exp",
		refreshTokens_aggregate:"authRefreshTokens_aggregate_bool_exp",
		roles:"authUserRoles_bool_exp",
		roles_aggregate:"authUserRoles_aggregate_bool_exp",
		securityKeys:"authUserSecurityKeys_bool_exp",
		securityKeys_aggregate:"authUserSecurityKeys_aggregate_bool_exp",
		ticket:"String_comparison_exp",
		ticketExpiresAt:"timestamptz_comparison_exp",
		totpSecret:"String_comparison_exp",
		updatedAt:"timestamptz_comparison_exp",
		userProviders:"authUserProviders_bool_exp",
		userProviders_aggregate:"authUserProviders_aggregate_bool_exp"
	},
	users_constraint: "enum" as const,
	users_delete_at_path_input:{

	},
	users_delete_elem_input:{

	},
	users_delete_key_input:{

	},
	users_insert_input:{
		createdAt:"timestamptz",
		defaultRoleByRole:"authRoles_obj_rel_insert_input",
		email:"citext",
		id:"uuid",
		lastSeen:"timestamptz",
		metadata:"jsonb",
		newEmail:"citext",
		otpHashExpiresAt:"timestamptz",
		refreshTokens:"authRefreshTokens_arr_rel_insert_input",
		roles:"authUserRoles_arr_rel_insert_input",
		securityKeys:"authUserSecurityKeys_arr_rel_insert_input",
		ticketExpiresAt:"timestamptz",
		updatedAt:"timestamptz",
		userProviders:"authUserProviders_arr_rel_insert_input"
	},
	users_max_order_by:{
		activeMfaType:"order_by",
		avatarUrl:"order_by",
		createdAt:"order_by",
		currentChallenge:"order_by",
		defaultRole:"order_by",
		displayName:"order_by",
		email:"order_by",
		id:"order_by",
		lastSeen:"order_by",
		locale:"order_by",
		newEmail:"order_by",
		otpHash:"order_by",
		otpHashExpiresAt:"order_by",
		otpMethodLastUsed:"order_by",
		passwordHash:"order_by",
		phoneNumber:"order_by",
		ticket:"order_by",
		ticketExpiresAt:"order_by",
		totpSecret:"order_by",
		updatedAt:"order_by"
	},
	users_min_order_by:{
		activeMfaType:"order_by",
		avatarUrl:"order_by",
		createdAt:"order_by",
		currentChallenge:"order_by",
		defaultRole:"order_by",
		displayName:"order_by",
		email:"order_by",
		id:"order_by",
		lastSeen:"order_by",
		locale:"order_by",
		newEmail:"order_by",
		otpHash:"order_by",
		otpHashExpiresAt:"order_by",
		otpMethodLastUsed:"order_by",
		passwordHash:"order_by",
		phoneNumber:"order_by",
		ticket:"order_by",
		ticketExpiresAt:"order_by",
		totpSecret:"order_by",
		updatedAt:"order_by"
	},
	users_obj_rel_insert_input:{
		data:"users_insert_input",
		on_conflict:"users_on_conflict"
	},
	users_on_conflict:{
		constraint:"users_constraint",
		update_columns:"users_update_column",
		where:"users_bool_exp"
	},
	users_order_by:{
		activeMfaType:"order_by",
		avatarUrl:"order_by",
		createdAt:"order_by",
		currentChallenge:"order_by",
		defaultRole:"order_by",
		defaultRoleByRole:"authRoles_order_by",
		disabled:"order_by",
		displayName:"order_by",
		email:"order_by",
		emailVerified:"order_by",
		id:"order_by",
		isAnonymous:"order_by",
		lastSeen:"order_by",
		locale:"order_by",
		metadata:"order_by",
		newEmail:"order_by",
		otpHash:"order_by",
		otpHashExpiresAt:"order_by",
		otpMethodLastUsed:"order_by",
		passwordHash:"order_by",
		phoneNumber:"order_by",
		phoneNumberVerified:"order_by",
		refreshTokens_aggregate:"authRefreshTokens_aggregate_order_by",
		roles_aggregate:"authUserRoles_aggregate_order_by",
		securityKeys_aggregate:"authUserSecurityKeys_aggregate_order_by",
		ticket:"order_by",
		ticketExpiresAt:"order_by",
		totpSecret:"order_by",
		updatedAt:"order_by",
		userProviders_aggregate:"authUserProviders_aggregate_order_by"
	},
	users_pk_columns_input:{
		id:"uuid"
	},
	users_prepend_input:{
		metadata:"jsonb"
	},
	users_select_column: "enum" as const,
	users_select_column_users_aggregate_bool_exp_bool_and_arguments_columns: "enum" as const,
	users_select_column_users_aggregate_bool_exp_bool_or_arguments_columns: "enum" as const,
	users_set_input:{
		createdAt:"timestamptz",
		email:"citext",
		id:"uuid",
		lastSeen:"timestamptz",
		metadata:"jsonb",
		newEmail:"citext",
		otpHashExpiresAt:"timestamptz",
		ticketExpiresAt:"timestamptz",
		updatedAt:"timestamptz"
	},
	users_stream_cursor_input:{
		initial_value:"users_stream_cursor_value_input",
		ordering:"cursor_ordering"
	},
	users_stream_cursor_value_input:{
		createdAt:"timestamptz",
		email:"citext",
		id:"uuid",
		lastSeen:"timestamptz",
		metadata:"jsonb",
		newEmail:"citext",
		otpHashExpiresAt:"timestamptz",
		ticketExpiresAt:"timestamptz",
		updatedAt:"timestamptz"
	},
	users_update_column: "enum" as const,
	users_updates:{
		_append:"users_append_input",
		_delete_at_path:"users_delete_at_path_input",
		_delete_elem:"users_delete_elem_input",
		_delete_key:"users_delete_key_input",
		_prepend:"users_prepend_input",
		_set:"users_set_input",
		where:"users_bool_exp"
	},
	uuid: `scalar.uuid` as const,
	uuid_comparison_exp:{
		_eq:"uuid",
		_gt:"uuid",
		_gte:"uuid",
		_in:"uuid",
		_lt:"uuid",
		_lte:"uuid",
		_neq:"uuid",
		_nin:"uuid"
	}
}

export const ReturnTypes: Record<string,any> = {
	cached:{
		ttl:"Int",
		refresh:"Boolean"
	},
	authProviderRequests:{
		id:"uuid",
		options:"jsonb"
	},
	authProviderRequests_aggregate:{
		aggregate:"authProviderRequests_aggregate_fields",
		nodes:"authProviderRequests"
	},
	authProviderRequests_aggregate_fields:{
		count:"Int",
		max:"authProviderRequests_max_fields",
		min:"authProviderRequests_min_fields"
	},
	authProviderRequests_max_fields:{
		id:"uuid"
	},
	authProviderRequests_min_fields:{
		id:"uuid"
	},
	authProviderRequests_mutation_response:{
		affected_rows:"Int",
		returning:"authProviderRequests"
	},
	authProviders:{
		id:"String",
		userProviders:"authUserProviders",
		userProviders_aggregate:"authUserProviders_aggregate"
	},
	authProviders_aggregate:{
		aggregate:"authProviders_aggregate_fields",
		nodes:"authProviders"
	},
	authProviders_aggregate_fields:{
		count:"Int",
		max:"authProviders_max_fields",
		min:"authProviders_min_fields"
	},
	authProviders_max_fields:{
		id:"String"
	},
	authProviders_min_fields:{
		id:"String"
	},
	authProviders_mutation_response:{
		affected_rows:"Int",
		returning:"authProviders"
	},
	authRefreshTokens:{
		createdAt:"timestamptz",
		expiresAt:"timestamptz",
		refreshToken:"uuid",
		user:"users",
		userId:"uuid"
	},
	authRefreshTokens_aggregate:{
		aggregate:"authRefreshTokens_aggregate_fields",
		nodes:"authRefreshTokens"
	},
	authRefreshTokens_aggregate_fields:{
		count:"Int",
		max:"authRefreshTokens_max_fields",
		min:"authRefreshTokens_min_fields"
	},
	authRefreshTokens_max_fields:{
		createdAt:"timestamptz",
		expiresAt:"timestamptz",
		refreshToken:"uuid",
		userId:"uuid"
	},
	authRefreshTokens_min_fields:{
		createdAt:"timestamptz",
		expiresAt:"timestamptz",
		refreshToken:"uuid",
		userId:"uuid"
	},
	authRefreshTokens_mutation_response:{
		affected_rows:"Int",
		returning:"authRefreshTokens"
	},
	authRoles:{
		role:"String",
		userRoles:"authUserRoles",
		userRoles_aggregate:"authUserRoles_aggregate",
		usersByDefaultRole:"users",
		usersByDefaultRole_aggregate:"users_aggregate"
	},
	authRoles_aggregate:{
		aggregate:"authRoles_aggregate_fields",
		nodes:"authRoles"
	},
	authRoles_aggregate_fields:{
		count:"Int",
		max:"authRoles_max_fields",
		min:"authRoles_min_fields"
	},
	authRoles_max_fields:{
		role:"String"
	},
	authRoles_min_fields:{
		role:"String"
	},
	authRoles_mutation_response:{
		affected_rows:"Int",
		returning:"authRoles"
	},
	authUserProviders:{
		accessToken:"String",
		createdAt:"timestamptz",
		id:"uuid",
		provider:"authProviders",
		providerId:"String",
		providerUserId:"String",
		refreshToken:"String",
		updatedAt:"timestamptz",
		user:"users",
		userId:"uuid"
	},
	authUserProviders_aggregate:{
		aggregate:"authUserProviders_aggregate_fields",
		nodes:"authUserProviders"
	},
	authUserProviders_aggregate_fields:{
		count:"Int",
		max:"authUserProviders_max_fields",
		min:"authUserProviders_min_fields"
	},
	authUserProviders_max_fields:{
		accessToken:"String",
		createdAt:"timestamptz",
		id:"uuid",
		providerId:"String",
		providerUserId:"String",
		refreshToken:"String",
		updatedAt:"timestamptz",
		userId:"uuid"
	},
	authUserProviders_min_fields:{
		accessToken:"String",
		createdAt:"timestamptz",
		id:"uuid",
		providerId:"String",
		providerUserId:"String",
		refreshToken:"String",
		updatedAt:"timestamptz",
		userId:"uuid"
	},
	authUserProviders_mutation_response:{
		affected_rows:"Int",
		returning:"authUserProviders"
	},
	authUserRoles:{
		createdAt:"timestamptz",
		id:"uuid",
		role:"String",
		roleByRole:"authRoles",
		user:"users",
		userId:"uuid"
	},
	authUserRoles_aggregate:{
		aggregate:"authUserRoles_aggregate_fields",
		nodes:"authUserRoles"
	},
	authUserRoles_aggregate_fields:{
		count:"Int",
		max:"authUserRoles_max_fields",
		min:"authUserRoles_min_fields"
	},
	authUserRoles_max_fields:{
		createdAt:"timestamptz",
		id:"uuid",
		role:"String",
		userId:"uuid"
	},
	authUserRoles_min_fields:{
		createdAt:"timestamptz",
		id:"uuid",
		role:"String",
		userId:"uuid"
	},
	authUserRoles_mutation_response:{
		affected_rows:"Int",
		returning:"authUserRoles"
	},
	authUserSecurityKeys:{
		counter:"bigint",
		credentialId:"String",
		credentialPublicKey:"bytea",
		id:"uuid",
		nickname:"String",
		transports:"String",
		user:"users",
		userId:"uuid"
	},
	authUserSecurityKeys_aggregate:{
		aggregate:"authUserSecurityKeys_aggregate_fields",
		nodes:"authUserSecurityKeys"
	},
	authUserSecurityKeys_aggregate_fields:{
		avg:"authUserSecurityKeys_avg_fields",
		count:"Int",
		max:"authUserSecurityKeys_max_fields",
		min:"authUserSecurityKeys_min_fields",
		stddev:"authUserSecurityKeys_stddev_fields",
		stddev_pop:"authUserSecurityKeys_stddev_pop_fields",
		stddev_samp:"authUserSecurityKeys_stddev_samp_fields",
		sum:"authUserSecurityKeys_sum_fields",
		var_pop:"authUserSecurityKeys_var_pop_fields",
		var_samp:"authUserSecurityKeys_var_samp_fields",
		variance:"authUserSecurityKeys_variance_fields"
	},
	authUserSecurityKeys_avg_fields:{
		counter:"Float"
	},
	authUserSecurityKeys_max_fields:{
		counter:"bigint",
		credentialId:"String",
		id:"uuid",
		nickname:"String",
		transports:"String",
		userId:"uuid"
	},
	authUserSecurityKeys_min_fields:{
		counter:"bigint",
		credentialId:"String",
		id:"uuid",
		nickname:"String",
		transports:"String",
		userId:"uuid"
	},
	authUserSecurityKeys_mutation_response:{
		affected_rows:"Int",
		returning:"authUserSecurityKeys"
	},
	authUserSecurityKeys_stddev_fields:{
		counter:"Float"
	},
	authUserSecurityKeys_stddev_pop_fields:{
		counter:"Float"
	},
	authUserSecurityKeys_stddev_samp_fields:{
		counter:"Float"
	},
	authUserSecurityKeys_sum_fields:{
		counter:"bigint"
	},
	authUserSecurityKeys_var_pop_fields:{
		counter:"Float"
	},
	authUserSecurityKeys_var_samp_fields:{
		counter:"Float"
	},
	authUserSecurityKeys_variance_fields:{
		counter:"Float"
	},
	beacon:{
		created_at:"timestamptz",
		entity:"entity",
		entity_aggregate:"entity_aggregate",
		mac:"macaddr",
		meta:"jsonb",
		pk:"Int",
		position_update:"position_update",
		position_update_aggregate:"position_update_aggregate",
		updated_at:"timestamptz",
		uuid:"uuid"
	},
	beacon_aggregate:{
		aggregate:"beacon_aggregate_fields",
		nodes:"beacon"
	},
	beacon_aggregate_fields:{
		avg:"beacon_avg_fields",
		count:"Int",
		max:"beacon_max_fields",
		min:"beacon_min_fields",
		stddev:"beacon_stddev_fields",
		stddev_pop:"beacon_stddev_pop_fields",
		stddev_samp:"beacon_stddev_samp_fields",
		sum:"beacon_sum_fields",
		var_pop:"beacon_var_pop_fields",
		var_samp:"beacon_var_samp_fields",
		variance:"beacon_variance_fields"
	},
	beacon_avg_fields:{
		pk:"Float"
	},
	beacon_max_fields:{
		created_at:"timestamptz",
		pk:"Int",
		updated_at:"timestamptz",
		uuid:"uuid"
	},
	beacon_min_fields:{
		created_at:"timestamptz",
		pk:"Int",
		updated_at:"timestamptz",
		uuid:"uuid"
	},
	beacon_mutation_response:{
		affected_rows:"Int",
		returning:"beacon"
	},
	beacon_stddev_fields:{
		pk:"Float"
	},
	beacon_stddev_pop_fields:{
		pk:"Float"
	},
	beacon_stddev_samp_fields:{
		pk:"Float"
	},
	beacon_sum_fields:{
		pk:"Int"
	},
	beacon_var_pop_fields:{
		pk:"Float"
	},
	beacon_var_samp_fields:{
		pk:"Float"
	},
	beacon_variance_fields:{
		pk:"Float"
	},
	bigint: `scalar.bigint` as const,
	buckets:{
		cacheControl:"String",
		createdAt:"timestamptz",
		downloadExpiration:"Int",
		files:"files",
		files_aggregate:"files_aggregate",
		id:"String",
		maxUploadFileSize:"Int",
		minUploadFileSize:"Int",
		presignedUrlsEnabled:"Boolean",
		updatedAt:"timestamptz"
	},
	buckets_aggregate:{
		aggregate:"buckets_aggregate_fields",
		nodes:"buckets"
	},
	buckets_aggregate_fields:{
		avg:"buckets_avg_fields",
		count:"Int",
		max:"buckets_max_fields",
		min:"buckets_min_fields",
		stddev:"buckets_stddev_fields",
		stddev_pop:"buckets_stddev_pop_fields",
		stddev_samp:"buckets_stddev_samp_fields",
		sum:"buckets_sum_fields",
		var_pop:"buckets_var_pop_fields",
		var_samp:"buckets_var_samp_fields",
		variance:"buckets_variance_fields"
	},
	buckets_avg_fields:{
		downloadExpiration:"Float",
		maxUploadFileSize:"Float",
		minUploadFileSize:"Float"
	},
	buckets_max_fields:{
		cacheControl:"String",
		createdAt:"timestamptz",
		downloadExpiration:"Int",
		id:"String",
		maxUploadFileSize:"Int",
		minUploadFileSize:"Int",
		updatedAt:"timestamptz"
	},
	buckets_min_fields:{
		cacheControl:"String",
		createdAt:"timestamptz",
		downloadExpiration:"Int",
		id:"String",
		maxUploadFileSize:"Int",
		minUploadFileSize:"Int",
		updatedAt:"timestamptz"
	},
	buckets_mutation_response:{
		affected_rows:"Int",
		returning:"buckets"
	},
	buckets_stddev_fields:{
		downloadExpiration:"Float",
		maxUploadFileSize:"Float",
		minUploadFileSize:"Float"
	},
	buckets_stddev_pop_fields:{
		downloadExpiration:"Float",
		maxUploadFileSize:"Float",
		minUploadFileSize:"Float"
	},
	buckets_stddev_samp_fields:{
		downloadExpiration:"Float",
		maxUploadFileSize:"Float",
		minUploadFileSize:"Float"
	},
	buckets_sum_fields:{
		downloadExpiration:"Int",
		maxUploadFileSize:"Int",
		minUploadFileSize:"Int"
	},
	buckets_var_pop_fields:{
		downloadExpiration:"Float",
		maxUploadFileSize:"Float",
		minUploadFileSize:"Float"
	},
	buckets_var_samp_fields:{
		downloadExpiration:"Float",
		maxUploadFileSize:"Float",
		minUploadFileSize:"Float"
	},
	buckets_variance_fields:{
		downloadExpiration:"Float",
		maxUploadFileSize:"Float",
		minUploadFileSize:"Float"
	},
	bytea: `scalar.bytea` as const,
	citext: `scalar.citext` as const,
	entity:{
		beacon:"beacon",
		beacon_pk:"Int",
		data:"jsonb",
		meta:"jsonb",
		pk:"Int",
		position_update:"position_update",
		position_update_aggregate:"position_update_aggregate",
		type:"String",
		uuid:"uuid"
	},
	entity_aggregate:{
		aggregate:"entity_aggregate_fields",
		nodes:"entity"
	},
	entity_aggregate_fields:{
		avg:"entity_avg_fields",
		count:"Int",
		max:"entity_max_fields",
		min:"entity_min_fields",
		stddev:"entity_stddev_fields",
		stddev_pop:"entity_stddev_pop_fields",
		stddev_samp:"entity_stddev_samp_fields",
		sum:"entity_sum_fields",
		var_pop:"entity_var_pop_fields",
		var_samp:"entity_var_samp_fields",
		variance:"entity_variance_fields"
	},
	entity_avg_fields:{
		beacon_pk:"Float",
		pk:"Float"
	},
	entity_max_fields:{
		beacon_pk:"Int",
		pk:"Int",
		type:"String",
		uuid:"uuid"
	},
	entity_min_fields:{
		beacon_pk:"Int",
		pk:"Int",
		type:"String",
		uuid:"uuid"
	},
	entity_mutation_response:{
		affected_rows:"Int",
		returning:"entity"
	},
	entity_stddev_fields:{
		beacon_pk:"Float",
		pk:"Float"
	},
	entity_stddev_pop_fields:{
		beacon_pk:"Float",
		pk:"Float"
	},
	entity_stddev_samp_fields:{
		beacon_pk:"Float",
		pk:"Float"
	},
	entity_sum_fields:{
		beacon_pk:"Int",
		pk:"Int"
	},
	entity_var_pop_fields:{
		beacon_pk:"Float",
		pk:"Float"
	},
	entity_var_samp_fields:{
		beacon_pk:"Float",
		pk:"Float"
	},
	entity_variance_fields:{
		beacon_pk:"Float",
		pk:"Float"
	},
	files:{
		bucket:"buckets",
		bucketId:"String",
		createdAt:"timestamptz",
		etag:"String",
		id:"uuid",
		isUploaded:"Boolean",
		mimeType:"String",
		name:"String",
		size:"Int",
		updatedAt:"timestamptz",
		uploadedByUserId:"uuid"
	},
	files_aggregate:{
		aggregate:"files_aggregate_fields",
		nodes:"files"
	},
	files_aggregate_fields:{
		avg:"files_avg_fields",
		count:"Int",
		max:"files_max_fields",
		min:"files_min_fields",
		stddev:"files_stddev_fields",
		stddev_pop:"files_stddev_pop_fields",
		stddev_samp:"files_stddev_samp_fields",
		sum:"files_sum_fields",
		var_pop:"files_var_pop_fields",
		var_samp:"files_var_samp_fields",
		variance:"files_variance_fields"
	},
	files_avg_fields:{
		size:"Float"
	},
	files_max_fields:{
		bucketId:"String",
		createdAt:"timestamptz",
		etag:"String",
		id:"uuid",
		mimeType:"String",
		name:"String",
		size:"Int",
		updatedAt:"timestamptz",
		uploadedByUserId:"uuid"
	},
	files_min_fields:{
		bucketId:"String",
		createdAt:"timestamptz",
		etag:"String",
		id:"uuid",
		mimeType:"String",
		name:"String",
		size:"Int",
		updatedAt:"timestamptz",
		uploadedByUserId:"uuid"
	},
	files_mutation_response:{
		affected_rows:"Int",
		returning:"files"
	},
	files_stddev_fields:{
		size:"Float"
	},
	files_stddev_pop_fields:{
		size:"Float"
	},
	files_stddev_samp_fields:{
		size:"Float"
	},
	files_sum_fields:{
		size:"Int"
	},
	files_var_pop_fields:{
		size:"Float"
	},
	files_var_samp_fields:{
		size:"Float"
	},
	files_variance_fields:{
		size:"Float"
	},
	jsonb: `scalar.jsonb` as const,
	macaddr: `scalar.macaddr` as const,
	map:{
		created_at:"timestamptz",
		floor_data:"jsonb",
		meta:"jsonb",
		name:"String",
		pk:"Int",
		position_update:"position_update",
		position_update_aggregate:"position_update_aggregate",
		uuid:"uuid"
	},
	map_aggregate:{
		aggregate:"map_aggregate_fields",
		nodes:"map"
	},
	map_aggregate_fields:{
		avg:"map_avg_fields",
		count:"Int",
		max:"map_max_fields",
		min:"map_min_fields",
		stddev:"map_stddev_fields",
		stddev_pop:"map_stddev_pop_fields",
		stddev_samp:"map_stddev_samp_fields",
		sum:"map_sum_fields",
		var_pop:"map_var_pop_fields",
		var_samp:"map_var_samp_fields",
		variance:"map_variance_fields"
	},
	map_avg_fields:{
		pk:"Float"
	},
	map_max_fields:{
		created_at:"timestamptz",
		name:"String",
		pk:"Int",
		uuid:"uuid"
	},
	map_min_fields:{
		created_at:"timestamptz",
		name:"String",
		pk:"Int",
		uuid:"uuid"
	},
	map_mutation_response:{
		affected_rows:"Int",
		returning:"map"
	},
	map_stddev_fields:{
		pk:"Float"
	},
	map_stddev_pop_fields:{
		pk:"Float"
	},
	map_stddev_samp_fields:{
		pk:"Float"
	},
	map_sum_fields:{
		pk:"Int"
	},
	map_var_pop_fields:{
		pk:"Float"
	},
	map_var_samp_fields:{
		pk:"Float"
	},
	map_variance_fields:{
		pk:"Float"
	},
	mutation_root:{
		deleteAuthProvider:"authProviders",
		deleteAuthProviderRequest:"authProviderRequests",
		deleteAuthProviderRequests:"authProviderRequests_mutation_response",
		deleteAuthProviders:"authProviders_mutation_response",
		deleteAuthRefreshToken:"authRefreshTokens",
		deleteAuthRefreshTokens:"authRefreshTokens_mutation_response",
		deleteAuthRole:"authRoles",
		deleteAuthRoles:"authRoles_mutation_response",
		deleteAuthUserProvider:"authUserProviders",
		deleteAuthUserProviders:"authUserProviders_mutation_response",
		deleteAuthUserRole:"authUserRoles",
		deleteAuthUserRoles:"authUserRoles_mutation_response",
		deleteAuthUserSecurityKey:"authUserSecurityKeys",
		deleteAuthUserSecurityKeys:"authUserSecurityKeys_mutation_response",
		deleteBucket:"buckets",
		deleteBuckets:"buckets_mutation_response",
		deleteFile:"files",
		deleteFiles:"files_mutation_response",
		deleteUser:"users",
		deleteUsers:"users_mutation_response",
		delete_beacon:"beacon_mutation_response",
		delete_beacon_by_pk:"beacon",
		delete_entity:"entity_mutation_response",
		delete_entity_by_pk:"entity",
		delete_map:"map_mutation_response",
		delete_map_by_pk:"map",
		delete_position_update:"position_update_mutation_response",
		delete_position_update_by_pk:"position_update",
		insertAuthProvider:"authProviders",
		insertAuthProviderRequest:"authProviderRequests",
		insertAuthProviderRequests:"authProviderRequests_mutation_response",
		insertAuthProviders:"authProviders_mutation_response",
		insertAuthRefreshToken:"authRefreshTokens",
		insertAuthRefreshTokens:"authRefreshTokens_mutation_response",
		insertAuthRole:"authRoles",
		insertAuthRoles:"authRoles_mutation_response",
		insertAuthUserProvider:"authUserProviders",
		insertAuthUserProviders:"authUserProviders_mutation_response",
		insertAuthUserRole:"authUserRoles",
		insertAuthUserRoles:"authUserRoles_mutation_response",
		insertAuthUserSecurityKey:"authUserSecurityKeys",
		insertAuthUserSecurityKeys:"authUserSecurityKeys_mutation_response",
		insertBucket:"buckets",
		insertBuckets:"buckets_mutation_response",
		insertFile:"files",
		insertFiles:"files_mutation_response",
		insertUser:"users",
		insertUsers:"users_mutation_response",
		insert_beacon:"beacon_mutation_response",
		insert_beacon_one:"beacon",
		insert_entity:"entity_mutation_response",
		insert_entity_one:"entity",
		insert_map:"map_mutation_response",
		insert_map_one:"map",
		insert_position_update:"position_update_mutation_response",
		insert_position_update_one:"position_update",
		updateAuthProvider:"authProviders",
		updateAuthProviderRequest:"authProviderRequests",
		updateAuthProviderRequests:"authProviderRequests_mutation_response",
		updateAuthProviders:"authProviders_mutation_response",
		updateAuthRefreshToken:"authRefreshTokens",
		updateAuthRefreshTokens:"authRefreshTokens_mutation_response",
		updateAuthRole:"authRoles",
		updateAuthRoles:"authRoles_mutation_response",
		updateAuthUserProvider:"authUserProviders",
		updateAuthUserProviders:"authUserProviders_mutation_response",
		updateAuthUserRole:"authUserRoles",
		updateAuthUserRoles:"authUserRoles_mutation_response",
		updateAuthUserSecurityKey:"authUserSecurityKeys",
		updateAuthUserSecurityKeys:"authUserSecurityKeys_mutation_response",
		updateBucket:"buckets",
		updateBuckets:"buckets_mutation_response",
		updateFile:"files",
		updateFiles:"files_mutation_response",
		updateUser:"users",
		updateUsers:"users_mutation_response",
		update_authProviderRequests_many:"authProviderRequests_mutation_response",
		update_authProviders_many:"authProviders_mutation_response",
		update_authRefreshTokens_many:"authRefreshTokens_mutation_response",
		update_authRoles_many:"authRoles_mutation_response",
		update_authUserProviders_many:"authUserProviders_mutation_response",
		update_authUserRoles_many:"authUserRoles_mutation_response",
		update_authUserSecurityKeys_many:"authUserSecurityKeys_mutation_response",
		update_beacon:"beacon_mutation_response",
		update_beacon_by_pk:"beacon",
		update_beacon_many:"beacon_mutation_response",
		update_buckets_many:"buckets_mutation_response",
		update_entity:"entity_mutation_response",
		update_entity_by_pk:"entity",
		update_entity_many:"entity_mutation_response",
		update_files_many:"files_mutation_response",
		update_map:"map_mutation_response",
		update_map_by_pk:"map",
		update_map_many:"map_mutation_response",
		update_position_update:"position_update_mutation_response",
		update_position_update_by_pk:"position_update",
		update_position_update_many:"position_update_mutation_response",
		update_users_many:"users_mutation_response"
	},
	position_update:{
		beacon:"beacon",
		beacon_pk:"Int",
		created_at:"timestamptz",
		entity:"entity",
		entity_pk:"Int",
		map:"map",
		map_pk:"Int",
		pk:"Int",
		x:"Float",
		y:"Float"
	},
	position_update_aggregate:{
		aggregate:"position_update_aggregate_fields",
		nodes:"position_update"
	},
	position_update_aggregate_fields:{
		avg:"position_update_avg_fields",
		count:"Int",
		max:"position_update_max_fields",
		min:"position_update_min_fields",
		stddev:"position_update_stddev_fields",
		stddev_pop:"position_update_stddev_pop_fields",
		stddev_samp:"position_update_stddev_samp_fields",
		sum:"position_update_sum_fields",
		var_pop:"position_update_var_pop_fields",
		var_samp:"position_update_var_samp_fields",
		variance:"position_update_variance_fields"
	},
	position_update_avg_fields:{
		beacon_pk:"Float",
		entity_pk:"Float",
		map_pk:"Float",
		pk:"Float",
		x:"Float",
		y:"Float"
	},
	position_update_max_fields:{
		beacon_pk:"Int",
		created_at:"timestamptz",
		entity_pk:"Int",
		map_pk:"Int",
		pk:"Int",
		x:"Float",
		y:"Float"
	},
	position_update_min_fields:{
		beacon_pk:"Int",
		created_at:"timestamptz",
		entity_pk:"Int",
		map_pk:"Int",
		pk:"Int",
		x:"Float",
		y:"Float"
	},
	position_update_mutation_response:{
		affected_rows:"Int",
		returning:"position_update"
	},
	position_update_stddev_fields:{
		beacon_pk:"Float",
		entity_pk:"Float",
		map_pk:"Float",
		pk:"Float",
		x:"Float",
		y:"Float"
	},
	position_update_stddev_pop_fields:{
		beacon_pk:"Float",
		entity_pk:"Float",
		map_pk:"Float",
		pk:"Float",
		x:"Float",
		y:"Float"
	},
	position_update_stddev_samp_fields:{
		beacon_pk:"Float",
		entity_pk:"Float",
		map_pk:"Float",
		pk:"Float",
		x:"Float",
		y:"Float"
	},
	position_update_sum_fields:{
		beacon_pk:"Int",
		entity_pk:"Int",
		map_pk:"Int",
		pk:"Int",
		x:"Float",
		y:"Float"
	},
	position_update_var_pop_fields:{
		beacon_pk:"Float",
		entity_pk:"Float",
		map_pk:"Float",
		pk:"Float",
		x:"Float",
		y:"Float"
	},
	position_update_var_samp_fields:{
		beacon_pk:"Float",
		entity_pk:"Float",
		map_pk:"Float",
		pk:"Float",
		x:"Float",
		y:"Float"
	},
	position_update_variance_fields:{
		beacon_pk:"Float",
		entity_pk:"Float",
		map_pk:"Float",
		pk:"Float",
		x:"Float",
		y:"Float"
	},
	query_root:{
		authProvider:"authProviders",
		authProviderRequest:"authProviderRequests",
		authProviderRequests:"authProviderRequests",
		authProviderRequestsAggregate:"authProviderRequests_aggregate",
		authProviders:"authProviders",
		authProvidersAggregate:"authProviders_aggregate",
		authRefreshToken:"authRefreshTokens",
		authRefreshTokens:"authRefreshTokens",
		authRefreshTokensAggregate:"authRefreshTokens_aggregate",
		authRole:"authRoles",
		authRoles:"authRoles",
		authRolesAggregate:"authRoles_aggregate",
		authUserProvider:"authUserProviders",
		authUserProviders:"authUserProviders",
		authUserProvidersAggregate:"authUserProviders_aggregate",
		authUserRole:"authUserRoles",
		authUserRoles:"authUserRoles",
		authUserRolesAggregate:"authUserRoles_aggregate",
		authUserSecurityKey:"authUserSecurityKeys",
		authUserSecurityKeys:"authUserSecurityKeys",
		authUserSecurityKeysAggregate:"authUserSecurityKeys_aggregate",
		beacon:"beacon",
		beacon_aggregate:"beacon_aggregate",
		beacon_by_pk:"beacon",
		bucket:"buckets",
		buckets:"buckets",
		bucketsAggregate:"buckets_aggregate",
		entity:"entity",
		entity_aggregate:"entity_aggregate",
		entity_by_pk:"entity",
		file:"files",
		files:"files",
		filesAggregate:"files_aggregate",
		map:"map",
		map_aggregate:"map_aggregate",
		map_by_pk:"map",
		position_update:"position_update",
		position_update_aggregate:"position_update_aggregate",
		position_update_by_pk:"position_update",
		user:"users",
		users:"users",
		usersAggregate:"users_aggregate"
	},
	subscription_root:{
		authProvider:"authProviders",
		authProviderRequest:"authProviderRequests",
		authProviderRequests:"authProviderRequests",
		authProviderRequestsAggregate:"authProviderRequests_aggregate",
		authProviderRequests_stream:"authProviderRequests",
		authProviders:"authProviders",
		authProvidersAggregate:"authProviders_aggregate",
		authProviders_stream:"authProviders",
		authRefreshToken:"authRefreshTokens",
		authRefreshTokens:"authRefreshTokens",
		authRefreshTokensAggregate:"authRefreshTokens_aggregate",
		authRefreshTokens_stream:"authRefreshTokens",
		authRole:"authRoles",
		authRoles:"authRoles",
		authRolesAggregate:"authRoles_aggregate",
		authRoles_stream:"authRoles",
		authUserProvider:"authUserProviders",
		authUserProviders:"authUserProviders",
		authUserProvidersAggregate:"authUserProviders_aggregate",
		authUserProviders_stream:"authUserProviders",
		authUserRole:"authUserRoles",
		authUserRoles:"authUserRoles",
		authUserRolesAggregate:"authUserRoles_aggregate",
		authUserRoles_stream:"authUserRoles",
		authUserSecurityKey:"authUserSecurityKeys",
		authUserSecurityKeys:"authUserSecurityKeys",
		authUserSecurityKeysAggregate:"authUserSecurityKeys_aggregate",
		authUserSecurityKeys_stream:"authUserSecurityKeys",
		beacon:"beacon",
		beacon_aggregate:"beacon_aggregate",
		beacon_by_pk:"beacon",
		beacon_stream:"beacon",
		bucket:"buckets",
		buckets:"buckets",
		bucketsAggregate:"buckets_aggregate",
		buckets_stream:"buckets",
		entity:"entity",
		entity_aggregate:"entity_aggregate",
		entity_by_pk:"entity",
		entity_stream:"entity",
		file:"files",
		files:"files",
		filesAggregate:"files_aggregate",
		files_stream:"files",
		map:"map",
		map_aggregate:"map_aggregate",
		map_by_pk:"map",
		map_stream:"map",
		position_update:"position_update",
		position_update_aggregate:"position_update_aggregate",
		position_update_by_pk:"position_update",
		position_update_stream:"position_update",
		user:"users",
		users:"users",
		usersAggregate:"users_aggregate",
		users_stream:"users"
	},
	timestamptz: `scalar.timestamptz` as const,
	users:{
		activeMfaType:"String",
		avatarUrl:"String",
		createdAt:"timestamptz",
		currentChallenge:"String",
		defaultRole:"String",
		defaultRoleByRole:"authRoles",
		disabled:"Boolean",
		displayName:"String",
		email:"citext",
		emailVerified:"Boolean",
		id:"uuid",
		isAnonymous:"Boolean",
		lastSeen:"timestamptz",
		locale:"String",
		metadata:"jsonb",
		newEmail:"citext",
		otpHash:"String",
		otpHashExpiresAt:"timestamptz",
		otpMethodLastUsed:"String",
		passwordHash:"String",
		phoneNumber:"String",
		phoneNumberVerified:"Boolean",
		refreshTokens:"authRefreshTokens",
		refreshTokens_aggregate:"authRefreshTokens_aggregate",
		roles:"authUserRoles",
		roles_aggregate:"authUserRoles_aggregate",
		securityKeys:"authUserSecurityKeys",
		securityKeys_aggregate:"authUserSecurityKeys_aggregate",
		ticket:"String",
		ticketExpiresAt:"timestamptz",
		totpSecret:"String",
		updatedAt:"timestamptz",
		userProviders:"authUserProviders",
		userProviders_aggregate:"authUserProviders_aggregate"
	},
	users_aggregate:{
		aggregate:"users_aggregate_fields",
		nodes:"users"
	},
	users_aggregate_fields:{
		count:"Int",
		max:"users_max_fields",
		min:"users_min_fields"
	},
	users_max_fields:{
		activeMfaType:"String",
		avatarUrl:"String",
		createdAt:"timestamptz",
		currentChallenge:"String",
		defaultRole:"String",
		displayName:"String",
		email:"citext",
		id:"uuid",
		lastSeen:"timestamptz",
		locale:"String",
		newEmail:"citext",
		otpHash:"String",
		otpHashExpiresAt:"timestamptz",
		otpMethodLastUsed:"String",
		passwordHash:"String",
		phoneNumber:"String",
		ticket:"String",
		ticketExpiresAt:"timestamptz",
		totpSecret:"String",
		updatedAt:"timestamptz"
	},
	users_min_fields:{
		activeMfaType:"String",
		avatarUrl:"String",
		createdAt:"timestamptz",
		currentChallenge:"String",
		defaultRole:"String",
		displayName:"String",
		email:"citext",
		id:"uuid",
		lastSeen:"timestamptz",
		locale:"String",
		newEmail:"citext",
		otpHash:"String",
		otpHashExpiresAt:"timestamptz",
		otpMethodLastUsed:"String",
		passwordHash:"String",
		phoneNumber:"String",
		ticket:"String",
		ticketExpiresAt:"timestamptz",
		totpSecret:"String",
		updatedAt:"timestamptz"
	},
	users_mutation_response:{
		affected_rows:"Int",
		returning:"users"
	},
	uuid: `scalar.uuid` as const
}

export const Ops = {
mutation: "mutation_root" as const,
	query: "query_root" as const,
	subscription: "subscription_root" as const
}